### ISSUE TITLE
Play wakewords recordings from web interface

### ISSUE THREAD

**Issue by maxbachmann** [rhasspy/rhasspy#101]
It is already possible to record wakewords for rhasspy-raven directly from the web interface. However it would be great to have a option to play them from there aswell to test whether the recording was good or not.
![raven_settings](https://user-images.githubusercontent.com/44199644/90553395-9934b880-e194-11ea-9023-832614cc5f4c.png)

**Comment by synesthesiam** [comment]
This will finally be added in 2.5.9
