### ISSUE TITLE
Add support for follow-up intent or intent chaining

### ISSUE THREAD

**Issue by sriramsv** [rhasspy/rhasspy#102]
It would be very useful to have follow-up intent where the voice assistant can ask for confirmation from the user or ask additional detail based on the initially triggered intent.
Rhasspy should support an intent-chaining mechanism wherein the context from the previous intent should be passed along to the follow-up intents similar to how it is in dialogflow. 

This way we can make rhasspy trigger a conversation without any voice command and still be able to match the confirmation answer to specific intents depending on other factors such as time of day, sensor event from HASS etc...

Hope this makes sense and would love to see this feature in rhasspy

**Comment by maxbachmann** [comment]
Rhasspy already support this kind of dialogue management https://rhasspy.readthedocs.io/en/latest/reference/#dialogue-manager.
The mqtt topic for this intent-chaining is `hermes/dialogueManager/continueSession`. It allows to provide:
- the `sessionId` of the dialogue session you would like to continue
- a `text` that it asks/answers before it continues to the next intent
- a `intentFilter` which is an array of all the intents, that are allowed in the next step of the dialogue (so you can e.g. only allow a yes/no intent)
- `sendIntentNotRecognized` which is just a flag whether it should send a IntentNotRecognized event when the follow up intent was not recognised
- and last but not least `customData` which can be any data you would like to pass on to the next intent

**Comment by sriramsv** [comment]
Ah, I see..thanks. It would be great to have a tutorial or examples given the documentation to understand the flow better

**Comment by maxbachmann** [comment]
@sriramsv we do not have a guide on this yet, but snips did use the same message protocol and has a guide on it, that should help you: https://docs.snips.ai/articles/platform/dialog/multi-turn-dialog
