### ISSUE TITLE
[QUESTION] Using laptop browser as microphone input

### ISSUE THREAD

**Issue by himuura** [rhasspy/rhasspy#103]
Quick question on the rhasspy setup, is it possible to use my laptop's internal microphone and mozilla browser (while viewing the localhost:12101) to "speak" with rhasspy? I'm asking this 'cause my 3b is sitting inside a drawer with my pi4, it would be kind of hard for the microphone to catch the word correctly. If it is indeed possible, how to set it up? Thanks in advance!

**Comment by synesthesiam** [comment]
This was originally a planned feature for Rhasspy, but both Firefox and Chrome have blocked microphone use when you don't have HTTPS enabled.

A different option for remote audio is to use [gstreamer](https://rhasspy.readthedocs.io/en/latest/audio-input/#gstreamer). Once you get it set up, you can just run the streaming script on your laptop and use it anywhere (inside or outside a browser).
