### ISSUE TITLE
Encountered a section with no Package: header

### ISSUE THREAD

**Issue by Santobert** [rhasspy/rhasspy#106]
I have tried to follow the installation procedure to install the `.deb` package on a raspberry pi zero w.

Btw. the raspberry pi zero uses armhf instead of armel:
```
$ dpkg-architecture | grep DEB_BUILD_ARCH=
DEB_BUILD_ARCH=armhf
```

Unfortunately the installation fails:
```
$ sudo apt install ./rhasspy_2.5_armhf.deb 
Paketlisten werden gelesen... Fehler!
E: Unterprozess Popen hat Fehlercode zurückgegeben (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /home/pi/rhasspy_2.5_armhf.deb
E: Die Paketliste oder die Statusdatei konnte nicht eingelesen oder geöffnet werden.
```

Do you need further information?

**Comment by synesthesiam** [comment]
The Pi Zero lies about its architecture for some reason. It's actually armel instead of armhf.

**Comment by Santobert** [comment]
> The Pi Zero lies about its architecture for some reason. It's actually armel instead of armhf.

Unfortunately both packages produce the same error. I've tried that before.

**Comment by synesthesiam** [comment]
Which version of Raspian is this on?

**Comment by Santobert** [comment]
The current one. 2020-somewhat, I think.

**Comment by synesthesiam** [comment]
Please try with the 2.5.8 Debian package and re-open issue if the problem persists.
