### ISSUE TITLE
Pocketsphinx and UPD Streaming

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy#110]
I was plaing with wakewords when I noticed that pocketsphinx (the only wakeword I got to understand me to date) does not work with UDP streaming enabled. Other wakewords have an input field for the UDP port, pocketshpinx doesn't.

I could get rhasspy to wake when I removed the UDP port, but with that included in my Audio Recording setup I can not get any reaction. I tried adding `"udp_audio": "12111"` to the pocketsphinx config but even then it didn't work.

Is this supposed to not work with pocketsphinx or is this a bug?

**Comment by synesthesiam** [comment]
This seems to have just been an accident; the UDP audio settings were left out of the web UI. I'm surprised you didn't get it to work by manually changing your settings though. This is working for me.

I'll get this into the next update, and let's see if it works for you then.

**Comment by synesthesiam** [comment]
Fixed in 2.5.6
