### ISSUE TITLE
Adjust the volume of beep.wav

### ISSUE THREAD

**Issue by capitaenz** [rhasspy/rhasspy#112]
Hello everyone,

Is there a (hidden) possibility to adjust the volume of beep * .wav?
The volume is too high for me, but the following speech output should be loud.
An exchange of files is not possible because of Docker.

**Comment by synesthesiam** [comment]
I have an idea of how to do this. It's complicated by the Hermes `playBytes` message just being WAV audio data, so anything extra like "50% volume" needs to be tucked into WAV metadata.

**Comment by DeadEnded** [comment]
You can also make a custom beep.wav file and change the mapping.  This would allow you to adjust its intensity and even change it all together.  I have my system using a few custom response this way.

The custom beep.wav file would be in your mapped volume so it would persist container recreation.

**Comment by benedikt-bartscher** [comment]
I think this shouldn't be an option in Rhasspy, as @DeadEnded mentioned you can use a custom .wav already. It would be cleaner to adjust the audio backend volume (alsa hardware/softvol or pulseaudio) via MQTT Commands.

**Comment by synesthesiam** [comment]
> I think this shouldn't be an option in Rhasspy, as @DeadEnded mentioned you can use a custom .wav already. It would be cleaner to adjust the audio backend volume (alsa hardware/softvol or pulseaudio) via MQTT Commands.

I agree in the general case, but I think it would be useful for when the user wants to independently control different types of audio output in Rhasspy.

My plan is to have the volume that `rhasspy-speakers-cli-hermes` plays a WAV at be 100% by default, but adjustable with extra metadata. The dialogue manager can send a volume scalar between 0 and 1 for beeps, and the text to speech services can do the same.

**Comment by synesthesiam** [comment]
Please try 2.5.8 and re-open if an issue is found.
