### ISSUE TITLE
Multiple Satellities in one Room

### ISSUE THREAD

**Issue by benedikt-bartscher** [rhasspy/rhasspy#113]
I have 2 Satellites in one Room, sadly i am not able to mix the Audio and send it to one rhasspy install. Is there any option to "group" those 2 Satellites? Currently both Satellites are triggering on Wake Word and it's a total mess.

**Comment by synesthesiam** [comment]
Hmmm...do you have both satellites connected to the base via HTTP or MQTT? If it's HTTP, it's hard to do much since they're not really aware of each other. But there might be an option for MQTT.

**Comment by benedikt-bartscher** [comment]
I have everything connect via MQTT. Any Ideas on how to accomplish this?

**Comment by Romkabouter** [comment]
Sure, you can set two different wakewords?

Otherwise, when both sat's here the wakeword, they respond
Can I ask what is the use of those 2 satellites in 1 room?

You can also set the same wakeword, but ignore 1 satellite in other service by adding the sat to listen to in the "Satellite siteIds" field, this should ignore the other.

**Comment by benedikt-bartscher** [comment]
Yes, but two different wakewords is lame.

I use one sat for the whole room and the other for my headset. I can't mix audio, because of the delay added by my USB Headset.

**Comment by Romkabouter** [comment]
I don't see any other options tbh.

But I also don't quite understand the use-case for having a sat for a whole room and another for a headset.
They basically control the same thing right? It's probably me, so sorry about that.

What might be possible, but also not a very nice solution, is to run 2 Rhasspy instances....

**Comment by benedikt-bartscher** [comment]
I am running multiple rhasspy instances in docker. But there is my problem: Both of them get triggerd at the same time.
Running Rhasspy on my Headset allows me to talk much quieter and in general recognition is much better. I don't wanna switch between the mics every time, that's not convenient either.

**Comment by Romkabouter** [comment]
I see, well you can separate the two instances and connect sat1 with server1 and sat2 with server2
This can be done by putting sat1 in all the Satellite ID field of server1 and sat2 in server2.
That way, sat1 does not trigger server2 and vice versa

What you cannot do with the same wakeword is to have a trigger from sat1 only, if sat2 also triggers the wakeword.
I suggest closing this issue and maybe go for a feature request here:
https://community.rhasspy.org/c/feature-requests/7

**Comment by synesthesiam** [comment]
> I have everything connect via MQTT. Any Ideas on how to accomplish this?

A small change to the dialogue manager could make this work. If it was aware that site ids were in a "group", then it could simply not start a new dialogue session if a member of the group already has one. So if a second wake up attempt comes in, it will be ignored.

I'm trying to think of what other uses grouping site ids this way might have.

**Comment by benedikt-bartscher** [comment]
> So if a second wake up attempt comes in, it will be ignored.

This is excatly what i need! Grouping site ids. It's useful in every case where you have more than 1 mic/sattelite close to each other (big rooms, headsets, smartphones). I could imagine many use cases.

**Comment by ghost** [comment]
nice idea.. But very often devices hear speakers from other rooms.. but these would not be "grouped"

What about something that checks for voice start time.. as sound waves travels at a set rate.. if any other device hears the wake word within X milliseconds only the first device should continue. It would not be very often that more than 2 devices get asked something all at the exact time in space.

My lounge room device can hear me in the kitchen speaking. but I would not "group" these devices 

thought?

**Comment by benedikt-bartscher** [comment]
Yes, a configurable delay in milliseconds would be nice (0 for disabled). As already mentioned it is very rare that 2 people close to each other need to call Rhasspy at the same time. So there is no real tradeoff, just benefit.

I think the most flexible way is to create custom groups, each with a custom delay of X milliseconds.

**Comment by joshward9182** [comment]
> My lounge room device can hear me in the kitchen speaking. but I would not "group" these devices
>
> thought?

These were exactly my thoughts.

I was about to raise this as a feature request, until I saw this issue thread.

I was hoping to for a way to say "turn on the light" and use the sat ID to determine in which room.
Don't want another light turning on due to it catching my voice also.

The Alexa works like this, which I'm trying to phase out.

**Comment by synesthesiam** [comment]
Here's what I'm thinking for this: assume there's a new configuration option for a site id "group separator". By default, this is not set and Rhasspy's behavior is unchanged.

As an example, let's say the group separator is set to "." (period). Assume you have 2 satellites and a base station with these site ids:

* `base`
* `living_room.satellite1`
* `living_room.satellite2`

Now, you wake up Rhasspy in the living room and both satellites detect it. With the group separator, the dialogue manager could split the site ids into `<group>.<name>` and notice that both `<group>` values are the same (`living_room`). In that case, the first session "wins" and the second session is quietly dropped.

Without the group separator, the second session would override the first (Snips' original behavior).

Thoughts?

**Comment by benedikt-bartscher** [comment]
I really like your approch, it doesn't even include changes to the GUI. Simply rename all sats and you are ready to go!

**Comment by joshward9182** [comment]
That looks like a good idea.

A couple of queries..

1)
The WebSocket API currently includes a 'sideId' property. Would this remain, or would you plan to split it in to 2 properties (e.g. groupId, siteId)?

2)
You mention if they are not grouped, the second session would override the first...

Say you have the following setup:
- base
- living_room.satellite1
- living_room.satellite2
- kitchen.satellite1

You speak a command in the living room, intended for the 'living_room' satellites.

The kitchen satellite then also picks up the speech in the distance. Would the kitchen satellite then override the living room satellite(s)?

**Comment by synesthesiam** [comment]
1. Anything passing through the dialogue manager would be split, so this should work even if it comes from the websocket API

2. In that case, I'd say it might be better to name things like this:

* base
* upstairs.living_room.satellite1
* upstairs.living_room.satellite2
* upstairs.kitchen.satellite1

I assume the living room and kitchen are "upstairs". With the proposed extension, you would want to group all satellites that could potentially activate at the same time. I left "living_room" and "kitchen" in the site ids assuming the intent handler might care to  do something with them.

**Comment by ghost** [comment]
Just checking the start time, any satellite that starts a session within something like 100ms of the first item are dropped

No name changing

Simple. Any item in any room that hears the wake word and starts a session.. first in wins

**Comment by synesthesiam** [comment]
In the Advanced settings, you can now set `dialogue.group_separator` as described above. For example:

```json
{
    "dialogue": {
        "group_separator": "."
    }
}
```

With that, you can set the site ids of two satellites to be something like `living_room.satellite1` and `living_room.satellite2` (everything before the "." is the "group id"). As long as one satellite in the same group has an active session, others will not be able to start one. So no more double wake ups :)

Please re-open the issue if you find a bug!

**Comment by xBelladonna** [comment]
I have been testing this out with two satellites in the same room, both using wakeword detection (Mycroft Precise custom trained networks) and am finding that this does not prevent double wakeups, in addition to blocking any dialogue sessions from the same satellite when one is already active. This is a bit of a problem since for some reason my dialogue sessions from any device take forever to end even after the intent has been handled, thus I cannot consecutively issue commands by waking it up again right after it's "finished" a session. Right now with the satellite grouping in use the way you've instructed here, I'm getting double wakeups *and* this blocking issue. Both my satellites wake up at either the exact same time, or within a few milliseconds of each other judging by the wake sound, the beeps are either exactly in phase and thus amplify to twice the volume and distort, or an almost unnoticeably short delay between them, I wonder if this has something to do with the failure to prevent double wakeups? Do you know what might be happening here?

Some logs for demonstration, you can see one of my satellites refusing to wake up again while it's "finished" dialogue session is still active for some reason. This does not happen without satellite grouping, I get consecutive wakeups every time.
```
[DEBUG:2020-11-28 22:51:25,040] rhasspyserver_hermes: Sent 299 char(s) to websocket
[DEBUG:2020-11-28 22:51:24,450] rhasspyserver_hermes: <- NluIntentNotRecognized(input='', site_id='bedroom.rhasspi', id=None, custom_data=None, session_id='bedroom.rhasspi-athena-rhasspi-4ef557b5-4161-4387-9668-13495e540c41')
[DEBUG:2020-11-28 22:51:00,986] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:43,197] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:40,814] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:38,078] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:35,924] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:33,755] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:31,135] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:28,677] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:26,500] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:23,652] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:50:23,651] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:50:23,649] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:50:23,648] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:50:23,646] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:50:23,641] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:50:23,633] rhasspyserver_hermes: <- NluIntent(input='never mind', intent=Intent(intent_name='NullAction', confidence_score=1.0), site_id='bedroom.rhasspi', id=None, slots=[], session_id='bedroom.rhasspi-athena-rhasspi-4ddcea6a-e69d-4e02-b686-cd29ef935064', custom_data=None, asr_tokens=[[AsrToken(value='never', confidence=1.0, range_start=0, range_end=5, time=None), AsrToken(value='mind', confidence=1.0, range_start=6, range_end=10, time=None)]], asr_confidence=None, raw_input='never mind', wakeword_id='athena-rhasspi', lang=None)
[DEBUG:2020-11-28 22:50:19,816] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:49:36,436] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,435] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,432] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,430] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,427] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,424] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,422] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,417] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,415] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,413] rhasspyserver_hermes: Sent 404 char(s) to websocket
[DEBUG:2020-11-28 22:49:36,394] rhasspyserver_hermes: <- NluIntent(input='never mind', intent=Intent(intent_name='NullAction', confidence_score=1.0), site_id='bedroom.rhasspi', id=None, slots=[], session_id='bedroom.rhasspi-athena-rhasspi-4d438631-1275-47b5-a5f6-ac3f69dd34b2', custom_data=None, asr_tokens=[[AsrToken(value='never', confidence=1.0, range_start=0, range_end=5, time=None), AsrToken(value='mind', confidence=1.0, range_start=6, range_end=10, time=None)]], asr_confidence=None, raw_input='never mind', wakeword_id='athena-rhasspi', lang=None)
[DEBUG:2020-11-28 22:49:32,406] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-rhasspi.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.rhasspi', session_id=None, send_audio_captured=None, lang=None)
```

Second satellite:
```
[DEBUG:2020-11-28 22:51:04,177] rhasspyserver_hermes: Sent 363 char(s) to websocket
[DEBUG:2020-11-28 22:51:04,175] rhasspyserver_hermes: <- NluIntent(input='shush', intent=Intent(intent_name='NullAction', confidence_score=1.0), site_id='bedroom.gp01', id=None, slots=[], session_id='bedroom.gp01-athena-gp01-62fb5133-0031-46be-99a3-163f894470b4', custom_data=None, asr_tokens=[[AsrToken(value='shush', confidence=1.0, range_start=0, range_end=5, time=None)]], asr_confidence=None, raw_input='shush', wakeword_id='athena-gp01', lang=None)
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,318] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,317] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,317] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,316] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:51:01,314] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-gp01.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.gp01', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:44,491] rhasspyserver_hermes: <- NluIntentNotRecognized(input='', site_id='bedroom.gp01', id=None, custom_data=None, session_id='bedroom.gp01-athena-gp01-d26dbe70-04ea-442c-a00d-dc61d3cc8b77')
[DEBUG:2020-11-28 22:50:20,100] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-gp01.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.gp01', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-11-28 22:50:01,665] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,664] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,664] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,664] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,664] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,663] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,663] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,663] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,663] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,663] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:50:01,663] rhasspyserver_hermes: Sent 290 char(s) to websocket
[DEBUG:2020-11-28 22:49:57,222] rhasspyserver_hermes: <- NluIntentNotRecognized(input='', site_id='bedroom.gp01', id=None, custom_data=None, session_id='bedroom.gp01-athena-gp01-3acef0e4-4562-4139-9032-b60945063bc6')
[DEBUG:2020-11-28 22:49:32,665] rhasspyserver_hermes: <- HotwordDetected(model_id='athena-gp01.pb', model_version='', model_type='personal', current_sensitivity=0.7, site_id='bedroom.gp01', session_id=None, send_audio_captured=None, lang=None)
```

**Comment by jerome83136** [comment]
Hello,

I'm having problems with multiple satellites and concurrent wakewords triggering.

I have:
**- 1 master node**
- - Name: master
- - Version: 2.5.10
- - Deployment: Docker
- - Arch: x86_64 / Debian Buster
- - Connexion: Ethernet

**- 1 satellite node**
- - Name: rdc.raspberrypi3
- - Version: 2.5.10
- - Deployment: .deb package
- - Arch: armhf / Debian Buster
- - Connexion: Wifi
- - Location: kitchen (can hear me from living room)
- - Wakeword: Raven (hey-flipper)

**- 1 satellite node**
- - Name: rdc.respeakercore2
- - Version: 2.5.10
- - Deployment: .deb package
- - Arch: armhf / Debian Buster
- - Connexion: Wifi
- - Location: living room (can hear me from the kitchen)
- - Wakeword: Raven (hey-flipper)

All nodes are using the same external MQTT server.

### The problem
The problem is that my satellites are triggering at the same time and are both trying to handle the intent at the same time.
I find it weird because:
- I configured "group_separator=." on my master
- I added a prefix "rdc." on my two nodes

I wonder if I did something wrong on the config ?


NB:
- I've tested and had the same behaviour on 2.5.9 and 2.5.10

- rdc.raspberrypi3 has its own secondary wakeword (hey-rasspy)
I noticed that when I say "hey rasspy", only rdc.raspberrypi3 wakes up and manage the command.
If I use 1 different wakeword for each satellite, I have no problems.

- I also noticed that Rhasspy is slower at handling requests when both satellites are running.
When I stop 1 of them, it gets lightning fast.

**Here are the configs:**
```
{
    "dialogue": {
        "group_separator": ".",
        "satellite_site_ids": "master,satellite1,satellite2,satellite3,rhasspy-sejour,rhasspy-rdc,rhasspy-salon,rdc.respeakercore2,rdc.raspberrypi3",
        "system": "rhasspy"
    },
    "handle": {
        "remote": {
            "url": "http://192.168.1.253:1880/gestionIntent"
        },
        "satellite_site_ids": "rhasspy-sejour,satellite1,satellite3,rhasspy-rdc,rhasspy-salon,rdc.respeakercore2,rdc.raspberrypi3",
        "system": "remote"
    },
    "intent": {
        "fuzzywuzzy": {
            "min_confidence": "0,5"
        },
        "satellite_site_ids": "master,satellite1,satellite2,satellite3,rhasspy-sejour,rhasspy-rdc,rhasspy-salon,rdc.respeakercore2,rdc.raspberrypi3",
        "system": "fsticuffs"
    },
    "mqtt": {
        "enabled": "true",
        "host": "192.168.1.253",
        "port": "1885",
        "site_id": "master"
    },
    "sounds": {
        "error": "${RHASSPY_PROFILE_DIR}/beep_ko.wav",
        "recorded": "${RHASSPY_PROFILE_DIR}/beep_ok.wav",
        "wake": "${RHASSPY_PROFILE_DIR}/beep_hi.wav"
    },
    "speech_to_text": {
        "satellite_site_ids": "master,satellite1,satellite2,satellite3,rhasspy-sejour,rhasspy-rdc,rhasspy-salon,rdc.respeakercore2,rdc.raspberrypi3",
        "system": "kaldi"
    },
    "text_to_speech": {
        "espeak": {
            "voice": "fr-FR"
        },
        "larynx": {
            "default_voice": "siwis"
        },
        "marytts": {
            "effects": {
                "effect_F0Scale_parameters": "f0Scale:1.1;",
                "effect_F0Scale_selected": "on",
                "effect_TractScaler_parameters": "amount:1;",
                "effect_TractScaler_selected": "on",
                "effect_Volume_parameters": "amount:0,5;",
                "effect_Volume_selected": "on"
            },
            "locale": "fr",
            "url": "http://192.168.1.253:59125/process",
            "voice": "enst-camille-hsmm",
            "volume": "1"
        },
        "satellite_site_ids": "master,satellite1,satellite2,satellite3,rhasspy-sejour,rhasspy-rdc,rhasspy-salon,rdc.respeakercore2,rdc.raspberrypi3",
        "system": "nanotts"
    }
}
```

```
{
    "dialogue": {
        "satellite_site_ids": "rdc.respeakercore2"
    },
    "handle": {
        "remote": {
            "url": "http://192.168.1.253:1880/gestionIntent"
        },
        "satellite_site_ids": "rdc.respeakercore2"
    },
    "intent": {
        "system": "hermes"
    },
    "microphone": {
        "arecord": {
            "device": "pulse",
            "siteId": "rdc.respeakercore2",
            "udp_audio_host": "127.0.0.1",
            "udp_audio_port": "8888"
        },
        "pyaudio": {
            "siteId": "rdc.respeakercore2",
            "udp_audio_host": "127.0.0.1",
            "udp_audio_port": "8888"
        },
        "system": "arecord"
    },
    "mqtt": {
        "enabled": "true",
        "host": "192.168.1.253",
        "port": "1885",
        "site_id": "rdc.respeakercore2"
    },
    "sounds": {
        "aplay": {
            "device": "pulse"
        },
        "system": "aplay",
        "wake": "${RHASSPY_PROFILE_DIR}/beep_hi.wav"
    },
    "speech_to_text": {
        "system": "hermes"
    },
    "text_to_speech": {
        "satellite_site_ids": "rdc.respeakercore2",
        "system": "hermes"
    },
    "wake": {
        "raven": {
            "keywords": {
                "hey-flipper": {
                    "enabled": true
                }
            },
            "udp_audio": "127.0.0.1:8888"
        },
        "satellite_site_ids": "rdc.respeakercore2",
        "system": "raven"
    },
    "rhasspy": {
        "listen_on_start": true
    }
}
```

```
{
    "dialogue": {
        "satellite_site_ids": "etage.raspberrypi3"
    },
    "handle": {
        "remote": {
            "url": "http://192.168.1.253:1880/gestionIntent"
        },
        "satellite_site_ids": "rdc.respeakercore2"
    },
    "intent": {
        "system": "hermes"
    },
    "microphone": {
        "arecord": {
            "device": "plughw:CARD=seeed8micvoicec,DEV=0",
            "siteId": "rdc.respeakercore2",
            "udp_audio_host": "127.0.0.1",
            "udp_audio_port": "8888"
        },
        "pyaudio": {
            "siteId": "rdc.raspberrypi3",
            "udp_audio_host": "127.0.0.1",
            "udp_audio_port": "8888"
        },
        "system": "pyaudio"
    },
    "mqtt": {
        "enabled": "true",
        "host": "192.168.1.253",
        "port": "1885",
        "site_id": "rdc.raspberrypi3"
    },
    "sounds": {
        "aplay": {
            "device": "pulse"
        },
        "system": "aplay",
        "wake": "${RHASSPY_PROFILE_DIR}/beep_hi.wav"
    },
    "speech_to_text": {
        "system": "hermes"
    },
    "text_to_speech": {
        "satellite_site_ids": "rdc.raspberrypi3",
        "system": "hermes"
    },
    "wake": {
        "raven": {
            "keywords": {
                "hey-flipper": {
                    "enabled": true
                },
                "hey-rhasspy": {
                    "enabled": true
                }
            },
            "udp_audio": "127.0.0.1:8888"
        },
        "satellite_site_ids": "rdc.raspberrypi3",
        "system": "raven"
    },
    "rhasspy": {
        "listen_on_start": true
    }
}
```

Feel free to request more traces and tests if needed.

Thank you very much for your help.

Best regards

**Comment by jerome83136** [comment]
Hello,

I noticed some mistakes in my rdc.raspberrypi3 satellite.
The site id wasn't correctly set for michrophone and handle

I updated it like this:

```
{
    "dialogue": {
        "satellite_site_ids": "rdc.raspberrypi3"
    },
    "handle": {
        "remote": {
            "url": "http://192.168.1.253:1880/gestionIntent"
        },
        "satellite_site_ids": "rdc.raspberrypi3"
    },
    "intent": {
        "system": "hermes"
    },
    "microphone": {
        "pyaudio": {
            "siteId": "rdc.raspberrypi3",
            "udp_audio_host": "127.0.0.1",
            "udp_audio_port": "8888"
        },
        "system": "pyaudio"
    },
    "mqtt": {
        "enabled": "true",
        "host": "192.168.1.253",
        "port": "1885",
        "site_id": "rdc.raspberrypi3"
    },
    "sounds": {
        "aplay": {
            "device": "pulse"
        },
        "system": "aplay",
        "wake": "${RHASSPY_PROFILE_DIR}/beep_hi.wav"
    },
    "speech_to_text": {
        "system": "hermes"
    },
    "text_to_speech": {
        "satellite_site_ids": "rdc.raspberrypi3",
        "system": "hermes"
    },
    "wake": {
        "raven": {
            "keywords": {
                "hey-flipper": {
                    "enabled": true
                }
            },
            "minimum_matches": "1",
            "probability_threshold": "0.6",
            "udp_audio": "127.0.0.1:8888",
            "vad_sensitivity": "1"
        },
        "satellite_site_ids": "rdc.raspberrypi3",
        "system": "raven"
    },
    "rhasspy": {
        "listen_on_start": true
    }
}
```

Now the behavior is:
- I say the wake word (hey rhasspy)
- Both satellites are catching it
- I say a command ("donne moi l'heure" English --> "give me the time")
- Both satellites are recognizing/handling the intent (GetTime)
- Both satellites are sending the response via TTS

All of this happens on the same timeframe on my satellites.

### Here are the logs:

**Node: master**

```
[DEBUG:2021-04-09 13:41:07,111] rhasspyserver_hermes: Sent 441 char(s) to websocket
[DEBUG:2021-04-09 13:41:05,781] rhasspyserver_hermes: Sent 437 char(s) to websocket
```

**Node: rdc.raspberrypi3**

```
[DEBUG:2021-04-09 13:36:27,027] rhasspyserver_hermes: Sent 437 char(s) to websocket
[DEBUG:2021-04-09 13:36:27,023] rhasspyserver_hermes: <- NluIntent(input="donne moi l'heure", intent=Intent(intent_name='GetTime', confidence_score=1.0), site_id='rdc.raspberrypi3', id=None, slots=[], session_id='rdc.raspberrypi3-hey-flipper-16260ade-35e0-47a4-84d0-965c76c344de', custom_data='hey-flipper', asr_tokens=[[AsrToken(value='donne', confidence=1.0, range_start=0, range_end=5, time=None), AsrToken(value='moi', confidence=1.0, range_start=6, range_end=9, time=None), AsrToken(value="l'heure", confidence=1.0, range_start=10, range_end=17, time=None)]], asr_confidence=None, raw_input="donne moi l'heure", wakeword_id='hey-flipper', lang=None)
[WARNING:2021-04-09 13:36:21,644] rhasspyserver_hermes: Dialogue management is disabled. ASR will NOT be automatically enabled.
[DEBUG:2021-04-09 13:36:21,643] rhasspyserver_hermes: <- HotwordDetected(model_id='/etc/rhasspy/profiles/fr/raven/hey-flipper/example-0.wav', model_version='', model_type='personal', current_sensitivity=0.6, site_id='rdc.raspberrypi3', session_id=None, send_audio_captured=None, lang=None)
```

**Node: rdc.respeakercore2**

```
[DEBUG:2021-04-09 11:41:07,146] rhasspyserver_hermes: Sent 441 char(s) to websocket
[DEBUG:2021-04-09 11:41:07,140] rhasspyserver_hermes: <- NluIntent(input="donne moi l'heure", intent=Intent(intent_name='GetTime', confidence_score=1.0), site_id='rdc.respeakercore2', id=None, slots=[], session_id='rdc.respeakercore2-hey-flipper-699c2a02-3302-4457-95af-4d20fd934fca', custom_data='hey-flipper', asr_tokens=[[AsrToken(value='donne', confidence=1.0, range_start=0, range_end=5, time=None), AsrToken(value='moi', confidence=1.0, range_start=6, range_end=9, time=None), AsrToken(value="l'heure", confidence=1.0, range_start=10, range_end=17, time=None)]], asr_confidence=None, raw_input="donne moi l'heure", wakeword_id='hey-flipper', lang=None)
[WARNING:2021-04-09 11:41:01,511] rhasspyserver_hermes: Dialogue management is disabled. ASR will NOT be automatically enabled.
[DEBUG:2021-04-09 11:41:01,506] rhasspyserver_hermes: <- HotwordDetected(model_id='/etc/rhasspy/profiles/fr/raven/hey-flipper/example-0.wav', model_version='', model_type='personal', current_sensitivity=0.6, site_id='rdc.respeakercore2', session_id=None, send_audio_captured=None, lang=None)
```

Dialogue management is disabled on my satellites, so I only configured **"dialogue.group_separator": "."** on the master.
Is it correct ?

Thank you for your help

Best regards

**Comment by synesthesiam** [comment]
I think I've figured out the problem here, and it will be fixed in the next update to 2.5.10.

During audio playback, it's possible for a second satellite to sneak in and start a new session. My automated tests didn't include audio, so I never saw it. I'm using locks now in the dialogue manager to prevent this behavior.

**Comment by jerome83136** [comment]
Great ! Thank you for the feedback.
Let's wait for the next update 🙂👍

**Comment by synesthesiam** [comment]
Hopefully fixed by now. Please let me know if this is still a problem.
