### ISSUE TITLE
Docker image not working on Raspberry Pi model B+ (armv6l)

### ISSUE THREAD

**Issue by wilmardo** [rhasspy/rhasspy#118]
The image pulls fine but isn't starting and throwing error 132. A quick search resulted that exit 132 is SIGILL (132-128=4) which means illegal instruction.
```console
# docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS                           PORTS               NAMES
13f7a4f7b91f        rhasspy/rhasspy:2.5.5   "bash /usr/lib/rhass…"   About a minute ago   Restarting (132) 8 seconds ago                       rhasspy
# arch
armv6l
```

I tried with both 2.5.6 and 2.5.5 but both result in the same exit 132.

I can see that there seems to be armv6 support in the Dockerfile:
https://github.com/rhasspy/rhasspy/blob/master/Dockerfile#L166

Is there anything more I can try? I currently have just a 4GB sdcard so trying to build the image on the Pi isn't an option :'(

**Comment by hawkeye217** [comment]
This command works for me on my Pi Zero: ``docker pull --platform linux/arm/v6 rhasspy/rhasspy``

Try pulling your arch explicitly.

**Comment by wilmardo** [comment]
Thanks that was the problem, the problem isn't strictly related to the Pi Zero as the docs suggest:
https://rhasspy.readthedocs.io/en/latest/installation/#raspberry-pi-zero

It is an underlying issue with Docker and armv6:
https://github.com/moby/moby/issues/41017
https://github.com/moby/moby/issues/34875
