### ISSUE TITLE
wrong download URL for torch prebuilt

### ISSUE THREAD

**Issue by snail59** [rhasspy/rhasspy#119]
Hello,

When installing rhasspy, I get this error:

`curl -sSfL -o "/home/rhasspy/rhasspy/download/torch-1.6.0-cp37-cp37m-linux_armv7l.whl" "https://github.com/synesthesiam/prebuilt-apps/releases/download/v1.0/torch-1.6.0-cp37-cp37m-armv7l.whl"`

`curl: (22) The requested URL returned error: 404 Not Found`

The error is in Makefile.in on line 474
$(DOCKER_ARCH) -> linux_$(PRECISE_ARCH)

diff --git a/Makefile.in b/Makefile.in
index 7ca5ae1..948d4a3 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -471,7 +471,7 @@ install-larynx: $(TORCH_WHEEL)
        "$(srcdir)/scripts/install/install-nanotts.sh" "$(NANOTTS_PRE_FILE)" "$(DESTDIR)$(prefix)"
 
 $(TORCH_WHEEL):
-       $(DO_DOWNLOAD) "$(TORCH_WHEEL)" "https://github.com/synesthesiam/prebuilt-apps/releases/download/v1.0/torch-1.6.0-cp37-cp37m-$(DOCKER_ARCH).whl"
+       $(DO_DOWNLOAD) "$(TORCH_WHEEL)" "https://github.com/synesthesiam/prebuilt-apps/releases/download/v1.0/torch-1.6.0-cp37-cp37m-linux_$(PRECISE_ARCH).whl"
 else # ENABLE_LARYNX
 larynx

**Comment by synesthesiam** [comment]
Thanks! Should be fixed in 918ddc43adf4092af9e7791063e7f45f632258cf
