### ISSUE TITLE
wake word precise does not work

### ISSUE THREAD

**Issue by j3mu5** [rhasspy/rhasspy#12]
Hello,

even without a currently working log i can at least test if the wake words are recognized. After detecting the wake words the wake wav is played.
A stop wav or error wav is not heard systematically. Sometimes (rarely) several stop wavs follow follow in a row - a strange bug.

Anyway, porcupine works great - the wake word reacts and a wake sound is played. But with Snowboy and Precise I had no success - here I don't get any feedback from the wake word.

**Comment by synesthesiam** [comment]
What hardware are you using?

**Comment by j3mu5** [comment]
I use Rhasspy on a Raspberry Pi4 (4 GB) and use docker-compose.
But I will try some more on a freshly installed Raspberry Pi - maybe I can get it right.

**Comment by j3mu5** [comment]
Porcupine and Snowboy both work now - I think the trick was to first restart the Docker container with the “Restart” button in the web interface and then restart the whole Docker container.
Or maybe it’s the current image of 2.5.0-pre. Nevertheless, it works!

Unfortunately Precise does not trigger yet. What I have tried so far:
Set a precise model from here or my self-trained one.

Investigate the start of Rhasspy with supervisord.log: Snowboy, Porcupine and Precise show no error message here, for all 3 I see something like this (unless I refer to a not existing wake word - then there are error messages insted):
2020-04-04 14:05:37,039 INFO spawned: 'wake_word' with pid 159

Follow start with “docker-compose up” or ws: Again, I don’t see a specific error message for Precise. It looks like precise is started.

I tried different wake words with a sensitivity of 0.5 or 0.9 and a trigger level of 3. Under no circumstances will the wakeword be triggered.

Is the sensitivity like Snowboy and Precise a value between 0 and 1, where higher = more sensitive?

What is the trigger level? I have found an explanation here (which I think refers to precise), but I don’t understand it completely. It sounds like: Lower trigger level, more sensitive.

Others also use trigger level = 2.

**Comment by synesthesiam** [comment]
Is this on `aarch64`? I found similar issues on a Pi Zero, but no problems on a Pi 3.

**Comment by j3mu5** [comment]
Thank you for making precise work! :) Coincidentally, I tried to get precise working with the [commands of ulno](https://community.rhasspy.org/t/did-anyone-get-precise-working-as-a-wakeword-system-for-rhasspy-2-5/750/4) today within the docker image - but unfortunately I didn't have a chance.

No, Raspbery Pi 4 with the current, updated version of Raspbian Buster seems to run `armv7l`.

With the command
`uname -a`
I get:
`Linux raspberrypi-docker-master 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux`

In my search for a way to display architecture I came across the following ([second post](https://www.raspberrypi.org/forums/viewtopic.php?t=245846), I'm not sure if this is helpful?)
_Raspbian is 32 bit and the ARM cores are running 32 bit mode (AArch32) which shows up as armv7._

**Comment by j3mu5** [comment]
Strange that there are differences between Pi 3 and Zero. With all I've done so far (much more superficially than you) I haven't seen any differences between Pi 3b+, 4 and Zero W.
Spontaneous idea: Could the difference be the OS (Buster, Stretch or older)?  Depending on the OS I had some problems or not.
