### ISSUE TITLE
MQTT messages signaling transition to STT delayed

### ISSUE THREAD

**Issue by okennedy** [rhasspy/rhasspy#120]
Configuration:
* Rhasspy version: 2.5.6 (Last working version 2.4.6)
* Hardware: raspberry pi 3+
* External MQTT server (manual mosquitto install)
* Wake word: Hermes MQTT ('hey snips')
* Audio recording: arecord
* Speech to text: Pocketsphynx

**Context**: I have a small support application that listens to MQTT and communicates state transitions in Rhasspy through LEDs.  For this, it is useful to know when audio capture has ended / when STT processing has started.

A message with the topic  `rhasspy/asr/default/default/audioCaptured` is indeed sent, but not until after STT completes.  As far as I can tell, there is presently no way to differentiate the audio capture phase from the STT phase.  

There seems to be a related issue with the recorded WAV, which also does not play until the STT phase completes.

**Comment by synesthesiam** [comment]
You should be able to get this information by listening for `hermes/asr/stopListening` which is sent once audio capture has finished (enough silence). It's this message, in fact, that triggers the STT process to start (in Pocketsphinx, anyways).

**Comment by okennedy** [comment]
Sorry for the delay in response, this is only a part-time project.

From what I'm seeing here, the `hermes/asr/stopListening` event is massively delayed, arriving as part of a burst along with the completion of the event.  Basically, I see two bursts of MQTT events:

mosquitto_sub reports the following burst of events after hotword detection:
```
hermes/hotword/default/detected
hermes/hotword/toggleOff
hermes/asr/toggleOff
hermes/audioServer/default/playBytes/591fecf1-4ee1-4f7f-b1ae-a219d54bdedc
hermes/audioServer/default/playFinished
hermes/hotword/toggleOn
hermes/asr/toggleOn
hermes/dialogueManager/sessionStarted
hermes/hotword/toggleOff
hermes/asr/startListening
```
And then the following burst of messages arrive after intent recognition
```
hermes/asr/textCaptured
rhasspy/asr/default/default/audioCaptured
hermes/hotword/toggleOff
hermes/asr/toggleOff
hermes/audioServer/default/playBytes/16462895-b647-4759-aef4-41cf0ae9ec42
hermes/audioServer/default/playFinished
hermes/hotword/toggleOn
hermes/asr/toggleOn
hermes/asr/stopListening
hermes/hotword/toggleOn
hermes/nlu/query
hermes/nlu/intentParsed
hermes/intent/GetTime
hermes/tts/say
hermes/audioServer/default/playBytes/735fcfc8-c4e4-4f7a-855a-e234966aa3b7
hermes/audioServer/default/playFinished
hermes/tts/sayFinished
hermes/asr/stopListening
hermes/dialogueManager/sessionEnded
hermes/hotword/toggleOn
```

`hermes/asr/stopListening` does indeed arrive, but not until after `hermes/asr/textCaptured`

I've tried this repeatedly and the ordering and arrival times of the messages are pretty consistent.

**Comment by synesthesiam** [comment]
OK, I think it would be useful to add a new message that is emitted by the STT services after silence has been detected, but *before* transcription begins.

@koenvervloesem any thoughts on this? Maybe something like `rhasspy/asr/recordingFinished`? I imagine this message would at least include `siteId` and `sessionId`, but it should be possible to also include the duration of recorded audio (which is known at this point in the STT process).

**Comment by koenvervloesem** [comment]
I have two questions:

- What would be the (semantic) difference then between `rhasspy/asr/{site_id}/{session_id}/audioCaptured` and this proposed `rhasspy/asr/recordingFinished`?
- Why is the `rhasspy/asr/{site_id}/{session_id}/audioCaptured` message sent so late?

**Comment by synesthesiam** [comment]
`audioCaptured` contains the actual WAV audio, and is optionally sent when a flag is set in the `startListening` message. I also sent it after `textCaptured` just in case it was a large amount of audio, so `textCaptured` would not be delayed.

**Comment by koenvervloesem** [comment]
Oh right, so there's currently no message that simply says "The audio capture is finished now". Then it would be a useful addition, yes. `rhasspy/asr/recordingFinished` seems like a clear name.

This message would then have a JSON payload with the `sessionId` and `siteId` attributes indeed. I don't think there's anything else that should be in it (at least for now, we can always add things like the duration later if there's a need), so then it's just the same information as `rhasspy/asr/{site_id}/{session_id}/audioCaptured` but without the WAV payload.

**Comment by okennedy** [comment]
That would be fantastic.  Thanks!

**Comment by synesthesiam** [comment]
This will be rolled into 2.5.8

**Comment by synesthesiam** [comment]
Please try 2.5.8 and re-open if there is an issue

**Comment by okennedy** [comment]
The `rhasspy/asr/recordingFinished` works as advertised!  Thanks for the addition! 

(and sorry for the really delayed response... I haven't had a chance to test before now)
