### ISSUE TITLE
speech-to-intent (A..Z)

### ISSUE THREAD

**Issue by Alex-Beh** [rhasspy/rhasspy#121]
May I know does rhasspy support the extraction of "Zone A Location B" from the speech? I would like to have something similar to [Number Ranges](https://rhasspy.readthedocs.io/en/latest/training/#number-ranges) but is in Alphabet?

**Comment by synesthesiam** [comment]
Alphabet ranges aren't supported, but it's pretty easy to put this right in `sentences.ini`:

```ini
[ZoneLocation]
alphabet = A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z

zone <alphabet>{zone} location <alphabet>{location}
```

**Comment by Alex-Beh** [comment]
Thanks for the reply. It works and the performance is amazing.

I have realized the wake up word detection don't work in the provided docker image. May I know do you have any idea on it?

Besides, how can I use Python script to trigger the detection and get the returned json file?

**Comment by synesthesiam** [comment]
The HTTP API is probably the easiest to use from Python. Just POST to [`/api/listen-for-command`](https://rhasspy.readthedocs.io/en/latest/reference/#api_listen_for_command) to wake Rhasspy up. The returned JSON will be the recognized intent.

> I have realized the wake up word detection don't work in the provided docker image. May I know do you have any idea on it?

It can be difficult to get microphone audio into Docker. You need to have `--device /dev/snd:/dev/snd` in your `docker run` command at least. Even then, there can be problems that are unique to your specific set up. Try switching between PyAudio and `arecord` input services in Rhasspy.
