### ISSUE TITLE
 rhasspymicrophone_pyaudio_hermes: -> AudioRecordError(error='[Errno -9997] Invalid sample rate', site_id='default', context='Device index: 0', session_id=None)

### ISSUE THREAD

**Issue by dfgas** [rhasspy/rhasspy#123]
I have install raspberry pi os on a pi 3b and using a usb microphone. 
how do i get rhasspy to record at a sample rate of 48000 instead of 16000.

**Comment by favarete** [comment]
Did you find a way?
