### ISSUE TITLE
Problem with TLS and profile.json

### ISSUE THREAD

**Issue by cedcox** [rhasspy/rhasspy#125]
Hello,

The variable ${RHASSPY_PROFILE_DIR} is not correctly replaced for ca_certs TLS configuration.

Here is my profile.json

`    "mqtt": {`
"enabled": "true",
"host": "rasp-test",
"password": "password",
"port": "8883",
"site_id": "master",
"tls": {
       "ca_certs": "${RHASSPY_PROFILE_DIR}/certs/ca.crt",
       "certfile": "${RHASSPY_PROFILE_DIR}/certs/rhasspy.crt",
       "enabled": true,
       "keyfile": "${RHASSPY_PROFILE_DIR}/certs/rhasspy.key"
},
"username": "rhasspy"
`

Here is the result in log :
`Nov  2 15:14:29 rasp-test rhasspy[29880]: [DEBUG:2020-11-02 15:14:29,145] rhasspyserver_hermes: MQTT TLS enabled: {'ca_certs': '${RHASSPY_PROFILE_DIR}/certs/ca.crt', 'certfile': '/home/pi/.config/rhasspy/profiles/fr/certs/rhasspy.crt', 'keyfile': '/home/pi/.config/rhasspy/profiles/fr/certs/rhasspy.key', 'cert_reqs': <VerifyMode.CERT_REQUIRED: 2>, 'tls_version': 2, 'ciphers': None}
`

We can see that the replace is not correctly done : `'ca_certs': '${RHASSPY_PROFILE_DIR}/certs/ca.crt'`

Thanks

Cédric

**Comment by synesthesiam** [comment]
Confirmed. Will be fixed in 2.5.8 :+1:

**Comment by synesthesiam** [comment]
Please try 2.5.8 and re-open if still an issue
