### ISSUE TITLE
Special characters stopped working between Rhasspy 2.5.5 and 2.5.7

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy#127]
There's a problem in the ASR that it doesn't handle special characters such as German “umlaute” (ü ö ä) correctly. It seems the bug has been introduced [between Rhasspy 2.5.5 and 2.5.7](https://community.rhasspy.org/t/rhasspy-mobile-app/1169/27?u=koan).

**Comment by synesthesiam** [comment]
I found that the `jsonify` function in the HTTP API was still forcing output to ASCII. This doesn't explain the emergence of the bug, though, since it's always been this way...

**Comment by synesthesiam** [comment]
Please try 2.5.8 and re-open if still an issue
