### ISSUE TITLE
Python Skill Code is missing an argument. 

### ISSUE THREAD

**Issue by LeducH** [rhasspy/rhasspy#133]
In the documentation the  python script `simple-skill.py` is missing something in line 33

```
  File "simple-skill.py", line 33
    client.publish("hermes/tts/say", json.dumps({"text": , "siteId": site_id}))
                                                         ^
SyntaxError: invalid syntax
```

What is needed?

**Comment by maxbachmann** [comment]
Thanks for reporting. This should be
```python
client.publish("hermes/tts/say", json.dumps({"text": sentence, "siteId": site_id}))
```

I updated the documentation accordingly. @synesthesiam are the docs automatically rebuilding or do you have to start a rebuild manually?

**Comment by synesthesiam** [comment]
They used to re-build automatically, but now ReadTheDocs seems to want me to click a button. Rebuilding now...

**Comment by maxbachmann** [comment]
It's in the docs now
