### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by benedikt-bartscher** [rhasspy/rhasspy#134]
Hello there, i just realized that the snips integration for home assistant works with rhasspy too (thanks to the hermes protocol). snips.say works out of the box for me. 
Sadly snips.say_action only publishes this mqtt message, but nothing happens in rhasspy:
```
hermes/dialogueManager/startSession {"siteId": "default", "customData": "", "init": {"type": "action", "text": "was", "canBeEnqueued": true, "intentFilter": ["WasGeht"]}}
hermes/dialogueManager/sessionQueued {"sessionId": "193ab2e7-5928-4b11-8d38-c2ac3f596e6a", "siteId": "default", "customData": ""}
```

https://www.home-assistant.io/integrations/snips/

**Comment by benedikt-bartscher** [comment]
Another little problem: If "snips:" is defined in HA's configuration.yaml, all tts answers are spoken 2 times

Edit: It seems like the snips integration receives intents via mqtt already, so if you use "snips:" in HA, you have to disable Intent Handling in Rhasspy. Otherwise all Intents are triggered two times

**Comment by benedikt-bartscher** [comment]
I figured it out. It works fine if you set 
`can_be_enqueued: false`
in your home assistant service call.

It seems like rhasspy is not supporting hermes/dialogueManager/sessionQueued messages yet.

Another Problem: Rhasspy starts listening while it is talking the question, so the question gets recognized again :(

**Comment by h4de5** [comment]
Are you running a separate snips installation? Or just HA and rhasspy? And thus using rhasspy's mqtt broker?

**Comment by benedikt-bartscher** [comment]
I am running everything in seperate docker containers:
- 3x Rhasspy Instances
- Home Assistant
- MQTT Broker

**Comment by h4de5** [comment]
Which mqtt broker are you using?

**Comment by benedikt-bartscher** [comment]
I am using the latest toke/mosquitto docker image

**Comment by h4de5** [comment]
If you just use it for forwarding mqtt messages you could use rhasspy's broker as well. Just open up the mqtt port on your rhassby base (12183) and let your satellites connect to it.
Will try out the snips: integration as well soon

**Comment by h4de5** [comment]
good to know side effect: if you let home-assistant and rhasspy share the same mqtt broker (and even disable intent handling on rhasspy side - like recommended above) - any example sentences you put into the recognize field on rhasspy's web site, will be handled (even if you do not check the handle box)

**Comment by reptilex** [comment]
I have almost the same setup as Benedikt with the difference that I only have 2 rhasspy's I also get the sound of the text configured in home assistant twice. And yes every test is actually being run for real. Should we use a second mosquitto instance just for rhasspy or just use the internal broker?

**Comment by reptilex** [comment]
Ok I figured out, that you don't need snips at all. At least if you are using mosquitto and intent_script in the configuration. And when you remove everything works and you only have speech once.

**Comment by Romkabouter** [comment]
@synesthesiam can be closed
