### ISSUE TITLE
blockages on larynx

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#136]
when I validate Larynx as a TTS interface I have a sign indicating that addons must be downloaded .... but it remains blocked !!!

    rhasspy/fr_larynx-siwis/checkpoint_270000.pth.tar
    rhasspy/fr_larynx-siwis/config.json
   rhasspy/fr_larynx-siwis/vocoder/checkpoint_450000.pth.tar
   rhasspy/fr_larynx-siwis/vocoder/config.json

the download is not done !!!
![Sans titre-1](https://user-images.githubusercontent.com/57072652/100068048-4a538a80-2e37-11eb-9fd9-e2bac6b7a2d7.gif)

**Comment by synesthesiam** [comment]
Please try again in 2.5.9 and re-open the issue if you still have problems. I went through all of the download links before the update.
