### ISSUE TITLE
Gstreamer microphone input documentation is incorrect

### ISSUE THREAD

**Issue by metronidazole** [rhasspy/rhasspy#138]
The rhasspy documentation regarding using gstreamer for microphone input is wrong:

https://rhasspy.readthedocs.io/en/latest/audio-input/#gstreamer

It says to use "gstreamer" with the following arguments "udpsrc port=12333 ! rawaudioparse use-sink-caps=false format=pcm pcm-format=s16le sample-rate=16000 num-channels=1 ! queue ! audioconvert ! audioresample ! filesink location=/dev/stdout"

However the rhasspy docker image does not contain any binary called "gstreamer". Instead you need to use "gst-launch-1.0" as the binary.

**Comment by synesthesiam** [comment]
Thank you!
