### ISSUE TITLE
Upgrade porcupine to version 1.9

### ISSUE THREAD

**Issue by lucianot54** [rhasspy/rhasspy#139]
Hi,

They are a new version of porcupine.

I tried to import new keyword files but I think it's crafted for porcupine 1.9. 
You have wake words like jarvis, alexa, hey google, etc.
https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files/

Thank you for you dev, rhasspy is awesome <3

Best regards

**Comment by Enc3ph4l0n** [comment]
Hi @synesthesiam,

I've forked and upgraded Porcupine to v1.9. However, I haven't yet had time to test and identify if any other changes are required.

I read there are "changes" to Picovoice licensing. I see "free" is limited to 1,000 voice interactions (per month). I don't know if this extends to Porcupine, or if the 1,000 limit has always been the case.

How would you like to proceed? Would you like to merge into a new branch to allow for any further changes and allow for testing?

https://github.com/Enc3ph4l0n/rhasspy-wake-porcupine-hermes/tree/Porcupine-V1.9

**Comment by synesthesiam** [comment]
Merged into 2.5.9. Thanks!
