### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/swagger_ui/static/text-to-speech'

### ISSUE THREAD

**Issue by d4rkdpg** [rhasspy/rhasspy#143]
on docker install I get this, fresh install Raspbian latest:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/swagger_ui/static/text-to-speech'

tried latest and 2.5.7 same results.

also NotFound: NotFound(404) on http://ip:12101/api/text-to-speech

any ideas?

**Comment by d4rkdpg** [comment]
anyone got any ideas

**Comment by synesthesiam** [comment]
What are you trying to do? If you want to use the text-to-speech endpoint, you need to `POST` to `/api/text-to-speech`.

If you browse to it instead, you're doing a `GET` request. This should fail, but it looks like the OpenAPI (swagger) page is picking it up for some reason and re-directing.

To view the API page, you can browse to http://ip:12101/api/

**Comment by d4rkdpg** [comment]
I am posting and it’s not working via node red.

Sent from my iPhone

On 11 Dec 2020, at 9:29 PM, Michael Hansen <notifications@github.com> wrote:

﻿

What are you trying to do? If you want to use the text-to-speech endpoint, you need to POST to /api/text-to-speech.

If you browse to it instead, you're doing a GET request. This should fail, but it looks like the OpenAPI (swagger) page is picking it up for some reason and re-directing.

To view the API page, you can browse to http://ip:12101/api/

**Comment by synesthesiam** [comment]
Should be fixed now in 2.5.9. Please re-open if the issue persists.
