### ISSUE TITLE
Make Install error

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#144]
an error occurs during make install:
/bin/bash: ligne 0 : cd: /home/pi/rhasspy/rhasspy-tts-larynx-hermes/larynx/TTS: Aucun fichier ou dossier de ce type
make: *** [Makefile:168: install-rhasspy] Error 1

**Comment by snail59** [comment]
it means "/bin/bash: ligne 0 : cd: /home/pi/rhasspy/rhasspy-tts-larynx-hermes/larynx/TTS: no such file or directory" ;-)
I think that git submodules is misiing this directory when using venv.

**Comment by snail59** [comment]
What I just did :

```
cd rhasspy-tts-larynx-hermes
git submodule add https://github.com/rhasspy/TTS larynx/TTS
```
