### ISSUE TITLE
Add a README in Home Assistant example

### ISSUE THREAD

**Issue by Djiit** [rhasspy/rhasspy#148]
Hey, 

I'm totally clueless on how to use the example about Home Assitant (https://github.com/rhasspy/rhasspy/tree/master/examples/homeassistant) . Sounds awesome to have a script to parse every entity on training... But I've no idea how to use it / where to put these files. A README and/or some entry in the doc would be much appreciated.

I'm ok to open a PR with some proper doc if anybody can quickly explain it to me here.

Cheers

**Comment by TheGroundZero** [comment]
A full tutorial on setup up Rhasspy with Home Assistant would be welcome.

So far I'm stuck at having a base station and satellite installed and managing to have the satellite "speak" via MQTT.
I sort of managed to the the "GetTime" intent working.
But I have no idea on how to capture the "HassTurnOn" intent that was created using the Home Assistant Example.

How can I capture the light/switch entity in the "HassTurnOn" intent and how do I link this back to a light/switch entity I can toggle or set the brightness of?

**Comment by Romkabouter** [comment]
Check out the new Wiki page:
https://github.com/rhasspy/rhasspy/wiki

You can always ask those questions on the community forum as well

https://community.rhasspy.org/
