### ISSUE TITLE
Ubuntu eoan depricated

### ISSUE THREAD

**Issue by mauxgu** [rhasspy/rhasspy#149]
**Ubuntu eoan is now depricated** and sources are moved to [Ubuntu old-releases](http://old-releases.ubuntu.com/ubuntu/dists/).

Once changing the base os (**rhasspy/Dockerfile**) from
`FROM ubuntu:eoan as build-ubuntu`
to
`FROM ubuntu:20.04 as build-ubuntu`
(20.04 == focal) Python3.7 is not supported anymore.

I'm very interested if it is possible to upgrade rhasspy to Python 3.8. Or do I need to use either depricated Ubuntu or Python packages?

What's your solution here? I'm uncertain in the best way to solve this.

**Comment by FoxRomeo** [comment]
Official container in https://hub.docker.com/r/rhasspy/rhasspy is build with this too.
Therefor this container will not be able to get any security fixes or be rebuild based on the current Dockerfile.

**Comment by synesthesiam** [comment]
I'm in the process of migrating the Docker images to `debian:buster` so I can keep Python 3.7 for the time being.

**Comment by heyryanw** [comment]
Are there any documented steps to getting all the build deps where they need to be in order to build using the build-docker.sh script? I'd like to take a stab at the work required to modernize those images.

**Comment by synesthesiam** [comment]
Thanks for the offer! I haven't had time to document all the steps, unfortunately. Here's a brief summary:

* Anything in `download/shared` is used  for all platforms
* Each platform (architecture) has a `download/<platform>` directory with Python wheels and pre-compiled binaries

When doing any `pip install` commands, the `download` directories are added with `--find-links`.

**Comment by heyryanw** [comment]
That seems to be the main issue I'm running into, actually, with the contents in the `./download` directory in general, and it's contents. I can't seem to catch where it's being generated or pulled from.

An example while attempting to execute the buildx context from the `build-docker.sh` script:
```ERROR [linux/arm/v6 build  2/45] COPY download/armv6/ /build/download/```

I must be missing something though.

**Comment by synesthesiam** [comment]
Docker images going forward will be based on Debian Buster.

> I can't seem to catch where it's being generated or pulled from.

I've changed this recently, so here's how it's *going* to work from here on:

* A `.gitkeep` file will be used to keep the `download` directory structure in git
* Everything in `download/shared` is copied into `$DOWNLOAD_DIR` in the container and is used with `pip install`
* Everything in `download/<platform>` is copied/used the same as `shared` but only for that platform (`amd64`, `armv7`, `arm64`, `armv6`)

It should be the case that if you have nothing in `download`, then everything is downloaded automatically during the build process.

**Comment by synesthesiam** [comment]
Docker images are now based on `debian:buster-slim`
