### ISSUE TITLE
recognition stops for 30 seconds

### ISSUE THREAD

**Issue by MartinMaier** [rhasspy/rhasspy#15]
I've just pulled the latest docker image (04/01/2020) and asserted that after nearly all positive intent recogitions the ok-beep will be interrupted and the next wake-up can't be done before 30 seconds.
[log001.log](https://github.com/rhasspy/rhasspy-voltron/files/4413538/log001.log)

**Comment by synesthesiam** [comment]
Hopefully corrected by now. Please re-open if not.
