### ISSUE TITLE
Session timeout should stop ASR listening

### ISSUE THREAD

**Issue by synesthesiam** [rhasspy/rhasspy#151]
ASR listens forever if session times out :frowning_face:

**Comment by KiboOst** [comment]
Also, consider adding a `Maximum Duration` setting in `Voice Command Settings`
If we usually speak short command it would allow to set a 6 or 8 sec max duration to shorten timeout when rhasspy doesn't manage to listen a command (noisy environement).

**Comment by synesthesiam** [comment]
I've added a "Max Seconds" setting to the ASR voice command settings. Please try it out and re-open the issue if there are still problems. Thanks!
