### ISSUE TITLE
site_ids for wake-word detection on mqtt base don't work

### ISSUE THREAD

**Issue by h4de5** [rhasspy/rhasspy#152]
Hi,

I am not sure in which repository to post this issue, because I could not find, the place where it is actually handled. 

my setup:
base .. doing all the work (including wake word detection)
![image](https://user-images.githubusercontent.com/6115324/102638409-b9cb4a00-4157-11eb-8bc3-b2c8bf5036e4.png)

and several raspberry satellites .. doing only audio in and out, the rest is connected via mqtt
![image](https://user-images.githubusercontent.com/6115324/102638429-bfc12b00-4157-11eb-96bb-7a6c24a9039c.png)

the wake word detection (using snowboy on the base) only works for one satellite, if I add exactly that one name into the comma-separated list like this:
![image](https://user-images.githubusercontent.com/6115324/102638601-10388880-4158-11eb-9dbb-b6d661343de4.png)

If i leave it blank or add multiple satellite names, the wake-word detection is no longer working for any of them. also enabling or disabling wake-word detection on the satellites, seems not to make any difference in that behavior.

Also I am not yet sure what the setting for "Output siteId" does in audio recording - for those satellites it's currently empty.

version 2.5.8
mqtt broker: rhasspy

I hope you can help me - best regards, and thanks again for that great piece of software!

**Comment by KiboOst** [comment]
Several strange things here.
Your base should be mqtt external as all your satellites, with base IP set
Dialogue management should be disable on satellites

Better ask on https://community.rhasspy.org/ instead of reporting issue/bug ?

**Comment by h4de5** [comment]
Base uses rhasspy's internal mqqt broker and satellites are connected to that using the external setting. This part does not make problems.

I think i tried disabling dialog managent before, but that didn't really make a difference.

As the wrong behaviour was easy to recreate, i assumed it is a bug, not a question.

**Comment by h4de5** [comment]
I thought I fixed that, but this problem still persists.

**Comment by Romkabouter** [comment]
Hi @h4de5 , can you confirm this fixed or still an issue? Seems to be a while ago

**Comment by h4de5** [comment]
are you cleaning up :)

I do not have a working setup at the moment, but the last time I checked, it did work for multiple satellites sending wake words.

**Comment by Romkabouter** [comment]
Yup, cleaning up a bit. To much old stuff. Thanks for closing
