### ISSUE TITLE
execution err in rpi3

### ISSUE THREAD

**Issue by DarielHG89** [rhasspy/rhasspy#153]
hi, i installed in home assistant with rpi3, when i try to execute this addon i get this err
[FATAL tini (6)] exec /run.sh failed: Exec format error

**Comment by synesthesiam** [comment]
This sounds like a Docker image was pulled for the wrong CPU architecture. Can you give some more details on your set up? Hass.io? 32-bit Raspberry Pi OS?

**Comment by DarielHG89** [comment]
hi, sorry for not close this issue, indeed that was that appends, i was using registry mirror and when i pull the latest tag i get the amd64, i found this when i try to install in raspbian, solved installing directly
