### ISSUE TITLE
Slots config in webui is broken (FileExistsError: [Errno 17] File exists: '/profiles/es/slots')

### ISSUE THREAD

**Issue by David-Lor** [rhasspy/rhasspy#154]
Trying to configure slots in Rhasspy webui (http://localhost:12101/slots):

I can write slots on the page, save them and launch the training:
![screenshot1](https://user-images.githubusercontent.com/17401854/102760458-ce852900-4375-11eb-897c-9de7c1b8508e.png)

However, when I reload the page, or switch to other section (like Sentences) and then Slots again, the textbox is empty, and the dropdown box is empty:
![screenshot2](https://user-images.githubusercontent.com/17401854/102760566-fd9b9a80-4375-11eb-8867-098b15cc6048.png)

If I create a new slots, and then Save Slots, this error shows up: `FileExistsError: [Errno 17] File exists: '/profiles/es/slots' `:
![imagen](https://user-images.githubusercontent.com/17401854/102760607-0ee4a700-4376-11eb-80bd-c9bfe2d08fca.png)

Using Docker image (Rhasspy 2.5.8), created with the command: `docker run -d -p 127.0.0.1:12101:12101 --name rhasspy -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v rhasspy-data:/profiles --device /dev/snd:/dev/snd rhasspy/rhasspy --user-profiles /profiles --profile es`

Log output:

```
[DEBUG:2020-12-21 10:18:40,884] rhasspyprofile.download: speech_to_text.system kaldi dummy = False


[DEBUG:2020-12-21 10:18:40,885] rhasspyprofile.download: speech_to_text.pocketsphinx.open_transcription True False = False


[DEBUG:2020-12-21 10:18:40,885] rhasspyprofile.download: speech_to_text.kaldi.open_transcription True False = False


[DEBUG:2020-12-21 10:18:40,885] rhasspyprofile.download: speech_to_text.pocketsphinx.mix_weight >0 0 = False


[DEBUG:2020-12-21 10:18:40,885] rhasspyprofile.download: speech_to_text.kaldi.mix_weight >0 0 = False


[DEBUG:2020-12-21 10:18:40,885] rhasspyprofile.download: text_to_speech.system larynx dummy = False


[DEBUG:2020-12-21 10:18:42,560] rhasspyprofile.download: speech_to_text.system kaldi dummy = False


[DEBUG:2020-12-21 10:18:42,560] rhasspyprofile.download: speech_to_text.pocketsphinx.open_transcription True False = False


[DEBUG:2020-12-21 10:18:42,560] rhasspyprofile.download: speech_to_text.kaldi.open_transcription True False = False


[DEBUG:2020-12-21 10:18:42,560] rhasspyprofile.download: speech_to_text.pocketsphinx.mix_weight >0 0 = False


[DEBUG:2020-12-21 10:18:42,561] rhasspyprofile.download: speech_to_text.kaldi.mix_weight >0 0 = False


[DEBUG:2020-12-21 10:18:42,561] rhasspyprofile.download: text_to_speech.system larynx dummy = False


[ERROR:2020-12-21 10:19:44,829] rhasspyserver_hermes: [Errno 17] File exists: '/profiles/es/slots'


Traceback (most recent call last):


  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request


    result = await self.dispatch_request(request_context)


  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request


    return await handler(**request_.view_args)


  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1704, in api_slots


    save_slots(slots_dir, new_slot_values, overwrite_all=overwrite_all)


  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 522, in save_slots


    slots_path.parent.mkdir(parents=True, exist_ok=True)


  File "/usr/lib/python3.7/pathlib.py", line 1258, in mkdir


    self._accessor.mkdir(self, mode)


FileExistsError: [Errno 17] File exists: '/profiles/es/slots'
```

**Comment by synesthesiam** [comment]
It looks like something went wrong at some point and Rhasspy created a *file* named `/profiles/es/slots` instead of directory. Now, it won't be able to use that as a directory until you manually delete it.

I'll add some code to check for this scenario and fix it, but I'm not sure how it happened in the first place.

**Comment by synesthesiam** [comment]
Added some more checks in 2.5.9
