### ISSUE TITLE
Add shutdown/reboot controls in web UI

### ISSUE THREAD

**Issue by synesthesiam** [rhasspy/rhasspy#157]
For people who only run Rhasspy on a device, it would be nice to be able to shut down or reboot the device directly from Rhasspy's web UI.

**Comment by RaspiManu** [comment]
Hey @synesthesiam,
Thank you very much for opening an issue with the idea.
It would also be great to have these buttons on a separate "Host" tab in the UI where you can see host system data, so you can recheck if for example your Pi 0W is struggeling with Rhasspy or if the load is ok.

**Comment by synesthesiam** [comment]
Restart/shutdown buttons coming in 2.5.9 :+1:

**Comment by RaspiManu** [comment]
Thank you very much, @synesthesiam 👍
