### ISSUE TITLE
[QUESTION or BUG ?] Custom converters

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#165]
Who can explain to me how to create a personal converter as shown in the documentation
as indicated :

You can define your own converters by placing a file in the converters directory of your profile. Like slot programs, this file should contain a shebang and be marked as executable (chmod +x ).
 
I reproduced the example given: created a file … \/profiles\/fr\/converters\/conv_jj  (with exe right and without extension)
>#!/usr/bin/env python3
import sys
import json
value = json.load(sys.stdin)
print(int(value))

i test with this intent :
>[testconv]
test (val):1 { value!conv_jj }

and I get an error -> NluException: “conv_jj”
with this log 👍 
>[ERROR:2021-01-12 14:42:16,241] rhasspynlu_hermes: handle_query
Traceback (most recent call last):
File “/home/pi/rhasspy/rhasspy-nlu-hermes/rhasspynlu_hermes/init.py”, line 104, in handle_query
fuzzy=self.fuzzy,
File “/home/pi/rhasspy/rhasspy-nlu/rhasspynlu/fsticuffs.py”, line 70, in recognize
extra_converters=extra_converters,
File “/home/pi/rhasspy/rhasspy-nlu/rhasspynlu/fsticuffs.py”, line 565, in path_to_recognition
converter_func = converters[last_converter.name]
KeyError: ‘convjj’
[DEBUG:2021-01-12 14:42:16,243] rhasspynlu_hermes: -> NluError(error="‘convjj’", site_id=‘Master’, context=‘voir test’, session_id=‘6634137f-dafc-4a02-957e-769ef555bbb4’)
[DEBUG:2021-01-12 14:42:16,244] rhasspynlu_hermes: Publishing 118 bytes(s) to hermes/error/nlu
[DEBUG:2021-01-12 14:42:16,248] rhasspyserver_hermes: Handling NluError (topic=hermes/error/nlu, id=1efac65f-f07e-4197-bdc3-b14527e88048)
[ERROR:2021-01-12 14:42:16,250] rhasspyserver_hermes: NluError(error="‘convjj’", site_id=‘Master’, context=‘voir test’, session_id=‘6634137f-dafc-4a02-957e-769ef555bbb4’)
[DEBUG:2021-01-12 14:42:16,253] rhasspyserver_hermes: -> HandleToggleOn(site_id=‘Master’)
[DEBUG:2021-01-12 14:42:16,254] rhasspyserver_hermes: Publishing 20 bytes(s) to rhasspy/handle/toggleOn
[ERROR:2021-01-12 14:42:16,255] rhasspyserver_hermes: ‘convjj’
Traceback (most recent call last):
File “/home/pi/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py”, line 1821, in full_dispatch_request
result = await self.dispatch_request(request_context)
File “/home/pi/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py”, line 1869, in dispatch_request
return await handler(**request_.view_args)
File “/home/pi/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/main.py”, line 1416, in api_text_to_intent
user_entities=user_entities,
File “/home/pi/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/main.py”, line 2641, in text_to_intent_dict
result = await core.recognize_intent(text, intent_filter=intent_filter)
File “/home/pi/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/init.py”, line 524, in recognize_intent
raise NluException(result.error)
rhasspyserver_hermes.NluException: ‘con_jj’

if I replace in the intention  **\!conv_test   by   \!int**     then it works!

Thank's Arpagor

**Comment by synesthesiam** [comment]
Reminder for myself about the problem with multiple values.

**Comment by arpagor62970** [comment]
following my research on converters to be able to pass several arguments I found that there are others than int - convert to integer, float - convert to real, bool - convert to boolean, False for zero or "false "(insensitive case), lower - lower-case, upper - upper-casebol,
I found others in fsticuffs: object, kind, unit, datetime ....
how to use them?
Thank's

**Comment by arpagor62970** [comment]
Hello, you tell me you have a solution ....
that in the future they should appear as a list of values
Did you make a change? (because I haven't seen an update on the Github)
or have I misinterpreted?
or you tell me that you know how to solve the problem of converter with multiple values and that will be solved .......... but later?
Thank you
Arpagor

**Comment by arpagor62970** [comment]
Good evening, I found the solution for multiple values!
see https://community.rhasspy.org/t/custom-converter-for-numbers-little-occupation-and-therefore-very-fast/2324?u=arpagor62970
in fact the concern came from
value = json.load (sys.stdin)
that I replaced by
value = sys.stdin.readlines ()
then just format the string from the list
and we get all the arguments
cordially
Arpagor
