### ISSUE TITLE
Wake/recorded/error sounds no longer play

### ISSUE THREAD

**Issue by hawkeye217** [rhasspy/rhasspy#17]
I'm testing the new ``2.5-pre`` version. I set up a master and satellite according to the [Getting Started Guide](https://rhasspy.github.io/rhasspy-voltron/tutorials.html#getting-started-guide) using an external MQTT server, and the wake/recorded sounds were working well until your recent commit (https://github.com/rhasspy/rhasspy-voltron/commit/1047c57bd9478ab2b010ffe4e4c90932867b9d15) to move the feedback sounds to the dialogue system.  

The Getting Started Guide says that I should enable Dialogue Management and set it to "Rhasspy" on the master and leave it disabled on the satellite when using MQTT.  However, the guide reverses that if using the remote HTTP server method.  

I found that if I used the remote HTTP server method, sounds worked.  But it seemed like the external MQTT method was performing slightly faster for me.

Is this a bug or do I just need to reconfigure something now that you've moved the sounds to be handled by the dialogue system?

**Comment by synesthesiam** [comment]
Hoping this is fixed by now. Please re-open if not.
