### ISSUE TITLE
cannot edit slots in sub-directories

### ISSUE THREAD

**Issue by h4de5** [rhasspy/rhasspy#170]
i've put my slots into sub-directories, as suggested in the docs: https://rhasspy.readthedocs.io/en/latest/training/#slot-directories

they still work, but they are no longer listed in the web gui.

**Comment by synesthesiam** [comment]
Thanks! This will be fixed in 2.5.10.

**Comment by h4de5** [comment]
probably ment 2.5.11 - it is not yet fixed in 2.5.10

**Comment by synesthesiam** [comment]
It will be in the "official" release of 2.5.10 :slightly_smiling_face:

**Comment by Romkabouter** [comment]
Hi @h4de5 , can you confirm this working in 2.5.11?

**Comment by h4de5** [comment]
yep. works fine. 
thanks for reminding!

![image](https://user-images.githubusercontent.com/6115324/143137159-d17f800b-d8ab-4175-b479-c3742f09e87f.png)
