### ISSUE TITLE
rhasspy-server-hermes seems to be missing on github

### ISSUE THREAD

**Issue by yosh774** [rhasspy/rhasspy#172]
on

`git clone --recursive https://github.com/rhasspy/rhasspy`

Error:

> Submodule path 'rhasspy-remote-http-hermes': checked out '24eb4a34c8ae7395874a8daf62f0aa13e2fea562'
> fatal: remote error: upload-pack: not our ref 0cb3d2b4afdd4c0412de2a5e56d37d980d195e6b
> fatal: the remote end hung up unexpectedly
> Fetched in submodule path 'rhasspy-server-hermes', but it did not contain 0cb3d2b4afdd4c0412de2a5e56d37d980d195e6b. Direct fetching of that commit failed.

rhasspy-server-hermes seems to be missing on github, would you be so kind as to re-commit this?

**Comment by yosh774** [comment]
also rhasspy-supervisor missing

**Comment by synesthesiam** [comment]
OK, pushed both projects. Let me know if there are still problems.
