### ISSUE TITLE
Training fails because of supposedly missing intent_graph.pickle.gz file.

### ISSUE THREAD

**Issue by andenbeere** [rhasspy/rhasspy#173]
Hello there,

thank you very much for this great piece of software.

Currently I am at a loss, whatever I do I cannot get my Rhasspy install to finish training. It always seems to miss the intent_graph.pickle.gz file, although it does exist in the profile directory. I tried both the rhasspy_2.5.8_amd64.deb and rhasspy_2.5.9_amd64.deb packages, on two different laptops (Ubuntu Mate 20.04). To clarify: I have a base - satellite setup with the two laptops being the satellites. Before that I had a working system with a bunch of intents. I don't know what changed, but now it stopped working.

Here is the relevant error message:
```
[DEBUG:2021-01-21 16:46:54,294] rhasspyserver_hermes: Handling AsrTrainSuccess (topic=rhasspy/asr/michael-laptop/trainSuccess, id=9d2a6ece-1684-463e-b751-b27977d97ef6)
[ERROR:2021-01-21 16:46:54,295] rhasspyserver_hermes: NluError(error="[Errno 2] No such file or directory: '/home/michael/.config/rhasspy/profiles/de/intent_graph.pickle.gz'", site_id='michael-laptop', context='669f73c1-f5cf-4ff7-9df9-45278a6d68b3', session_id='669f73c1-f5cf-4ff7-9df9-45278a6d68b3')
[ERROR:2021-01-21 16:46:54,295] rhasspyserver_hermes: [Errno 2] No such file or directory: '/home/michael/.config/rhasspy/profiles/de/intent_graph.pickle.gz'
Traceback (most recent call last):
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/usr/local/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1321, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 475, in train
    raise TrainingFailedException(reason=nlu_response.error)
rhasspyserver_hermes.TrainingFailedException: [Errno 2] No such file or directory: '/home/michael/.config/rhasspy/profiles/de/intent_graph.pickle.gz'
 ```
And here the actual directory content (the pickle file was created during the training run):
```
~/.config/rhasspy/profiles/de$ ls -l
insgesamt 40
-rw-rw-r-- 1 michael michael 3541 Jan 21 16:46 intent_graph.pickle.gz
drwxrwxr-x 3 michael michael 4096 Jan 21 16:46 kaldi
-rw-rw-r-- 1 michael michael   28 Jan 21 16:46 kaldi_custom_words.txt
-rw-rw-r-- 1 michael michael   28 Jan 21 16:46 kaldi_unknown_words.txt
-rw-rw-r-- 1 michael michael  472 Jan 21 16:29 profile.json
-rw-r--r-- 1 michael michael 1059 Jan 21 16:39 sentences.ini
-rw-rw-r-- 1 michael michael 2140 Jan 21 16:44 supervisord.conf
-rw-rw-r-- 1 michael michael 4780 Jan 21 16:44 supervisord.log
-rw-rw-r-- 1 michael michael    7 Jan 21 16:44 supervisord.pid
```

Attached are the detailed logs and my profile file. If you need anything else, I'll do my best to provide it.

Regards
Michael

[rhasspy-satellite.log](https://github.com/rhasspy/rhasspy/files/5850579/rhasspy-satellite.log)

{
    "dialogue": {
        "system": "hermes"
    },
    "intent": {
        "system": "hermes"
    },
    "microphone": {
        "arecord": {
            "device": "pulse"
        },
        "system": "arecord"
    },
    "mqtt": {
        "enabled": "true",
        "host": "192.168.178.34",
        "port": "1883",
        "site_id": "michael-laptop"
    },
    "speech_to_text": {
        "system": "kaldi"
    },
    "wake": {
        "system": "porcupine"
    }
}

**Comment by neildownie** [comment]
Having the same problem with intent_graph.pickle.gz.
On a Pi 4 with no satellites and fresh install

**Comment by solidssss** [comment]
Same.

**Comment by thundergreen** [comment]
Same on hassio addon install with raspberry pi satellite

**Comment by maxmopp** [comment]
Same problem here, training on client: 
No such file or directory:  /profiles/en/intent_graph.pickle.gz
check at master: 
No such file or directory: '/profiles/en/intent_graph.pickle.gz'", site_id='unicorn', context='handle_train' ...
Temporary fix on master:
ln -s /share/rhasspy/profiles/en /profiles/
Training does succeed on client

**Comment by thundergreen** [comment]
If I well understand.. Training is done by master not slaves .. Am I right
mister Dev ?

maxmopp <notifications@github.com> schrieb am Di., 9. März 2021, 18:13:

**Comment by synesthesiam** [comment]
Sorry for the very late reply. I think @thundergreen is on the right path here.

Training typically happens on the base station (master). From the log that @andenbeere posted initially, it looks like the ASR service (Kaldi) is running on the satellite but not the NLU service (fsticuffs).

The typical base/satellite set up would be to have ASR and NLU on the base, where you also do the training. And then have each satellite either use Remote HTTP or Hermes MQTT for ASR/NLU, depending on whether or not you have a shared MQTT broker.
