### ISSUE TITLE
/api​/text-to-speech ignoring voice parameter

### ISSUE THREAD

**Issue by jasonhildebrand** [rhasspy/rhasspy#178]
In `rhasspy-server-hermes/web/swagger.yaml` I see that the text-to-speech endpoint takes an optional voice parameter to override the configured voice.

But when I tried it out, it did not work, and I could see in the rhasspy logs that the bash command to invoke tts (I'm using marytts) did not include the voice parameter I passed.

Is the intent to provide support for this parameter?

I would like this to work.  My question is mostly whether it makes any sense for me to jump in and try to implement this, or whether plans have changed and you are not aiming/wanting to implement this anymore.

**Comment by synesthesiam** [comment]
I've made some changes that will be in 2.5.10 specifically for MaryTTS. A current limitation of Hermes is that only a `lang` property is available. I may add a new property in the future, but for now I've made it so that you can put `<LANGUAGE>/<VOICE>` in the `?voice` parameter.

**Comment by synesthesiam** [comment]
Should be updated in latest 2.5.10. Please comment if you'd like to continue the discussion.
