### ISSUE TITLE
DialogManager not respecting the text field when asked to end a session.

### ISSUE THREAD

**Issue by NathanC** [rhasspy/rhasspy#18]
When publishing to `hermes/dialogueManager/endSession` it looks like the text field defined in the [spec](https://docs.snips.ai/reference/dialogue#outbound-message-2) isn't respected (i.e., doesn't lead to a TTS message).

Looks like the dataclass that's sinkholing this is [here](https://github.com/rhasspy/rhasspy-hermes/blob/master/rhasspyhermes/dialogue.py#L131-L132). 

If no-one else wants to I can open a PR for this at some point, seems like a good way to get more familiar with the codebase.

**Comment by synesthesiam** [comment]
Thanks, fix is in progress :+1:

**Comment by NathanC** [comment]
@synesthesiam Thanks for the super quick response and change! I was excited when I woke up and my PR for the other issue was merged and a change was made for this one, definitely encourages me to contribute more :)

I pulled the latest image, and it looks like there's an error when I provide a "text" field in the session:

```
[ERROR:2020-04-04 10:21:22,684] asyncio: Task exception was never retrieved
future: <Task finished coro=<HermesClient.publish_all() done, defined at /usr/lib/rhasspy-voltron/rhasspy-hermes/rhasspyhermes/client.py:315> exception=AttributeError("'NoneType' object has no attribute 'siteId'")>
Traceback (most recent call last):
  File "/usr/lib/rhasspy-voltron/rhasspy-dialogue-hermes/rhasspydialogue_hermes/__init__.py", line 344, in handle_end
    end_session.text, siteId=self.session.siteId
AttributeError: 'NoneType' object has no attribute 'siteId'
```

So it looks like it's erring out [here](https://github.com/rhasspy/rhasspy-dialogue-hermes/blob/master/rhasspydialogue_hermes/__init__.py#L344).

Looks like line 336 calls into `self.end_session()`, which sets the session to None inside of it, so by the time it gets to 344 the session is None and the error is raised.

Moving the block above it might work, or capturing in an intermediate variable-- haven't looked much at the lifecycle of a session in the code so idk what the right pattern is. 

For the flow, I can't remember the Snips behavior, but I'd expect the session to only end after it gets back a success message from the tts component (or hits some timeout). wdyt?

**Comment by NathanC** [comment]
Yeah looking at the code a bit more I think inverting the two blocks would achieve the right behavior per hermes spec and fix the error. `self.say` has an await inside it, so the session shouldn't end before tts returns or times out.

side note: I love how expressive the typing is in this codebase, more than most python projects I've seen!
