### ISSUE TITLE
Inconsistent Home Assistant URL naming

### ISSUE THREAD

**Issue by MarvinWalther** [rhasspy/rhasspy#188]
I was trying to follow the [Home Assistant example](https://github.com/rhasspy/rhasspy/tree/master/examples/homeassistant), especially the slot program to download all Home Assistant entities automatically.
But I always got the following error while training:
`×AssertionError: No output from ['/profiles/de/slot_programs/hass/entities']`.

It took me a while to figure out, that the cause was just a little slash:

In [the docs](https://rhasspy.readthedocs.io/en/latest/intent-handling/) there is written, you should set the url to Home Assistant as follows:
`"url": "http://hassio/homeassistant/"` (with slash at the end).
But if you're doing that, the slot program from the [Home Assistant example](https://github.com/rhasspy/rhasspy/tree/master/examples/homeassistant) won't work, because in [_slot_programs/hass/entities_, line 40](https://github.com/rhasspy/rhasspy/blob/master/examples/homeassistant/profile/slot_programs/hass/entities#L40) it says
`"${url}/api/states"  | \` and not
`"${url}api/states"  | \`.
Leading to a double-slash and the error while running the script.

Is there something, I miss or should the url of Home Assistant be written without slash in the _profile.json_ (and the docs):
`"url": "http://hassio/homeassistant"`?

Also: Isn't there the port missing? Thus:
`"url": "http://ip_of_home_assistant_instance:8123"`.
This last one is, what worked for me at least...

**Comment by synesthesiam** [comment]
Thanks for catching this! I'll be updating the example with an extra line:

```
# Strip final slash, if present
url="${url%/}"
```

> Also: Isn't there the port missing?

I don't think the port is necessary from within Hass.io, but I haven't tested it in a while.

**Comment by synesthesiam** [comment]
Should be fixed in latest `master`.
