### ISSUE TITLE
Pi Zero with ReSpeaker 2 Hat - 718 Segmentation fault - Fresh Install

### ISSUE THREAD

**Issue by ZillionPrey** [rhasspy/rhasspy#193]
Hi Guys,

I tried to setup Rhasspy since I wanted to build a sattelite from a Pi with the ReSpeaker Hat.

Installation worked fine, I also have the ReSpeaker drivers installed.

This is what I see when I'm trying to start Rhasspy:

<img width="863" alt="Screenshot at Feb 24 18-18-33" src="https://user-images.githubusercontent.com/6315513/109039145-bf4f8e00-76cc-11eb-9dcb-eacb12533aae.png">

**Comment by h4de5** [comment]
did you see the notice in the manual about needed experimental feature for rpi zero? 
https://rhasspy.readthedocs.io/en/latest/installation/

**Comment by doodlebro** [comment]
Doesn't look like they are using docker, though. I don't think the experimental feature is required for the .deb installed version.

**Comment by h4de5** [comment]
oh. you are right.

**Comment by ZillionPrey** [comment]
Easy fix, I skipped or overread the text that said "The Pi might lie to You and say armhf instead of armel".

So it was my mistake and used the wrong image. Sorry!
