### ISSUE TITLE
Configurable port

### ISSUE THREAD

**Issue by Braincoke** [rhasspy/rhasspy#194]
Hi,

I like to use docker [macvlan](https://docs.docker.com/network/macvlan/) for my containers.
Because of this I cannot map ports and I have to configure them in the application directly.
I would love it if the port was configurable so that accessing my rhasspy instance is more intuitive (e.g. http://rhasspy instead of http://rhasspy:12101).

Of course this isn't a big issue and more of an enhancement proposal.

**Comment by synesthesiam** [comment]
Just pass `--http-port <PORT>` when you run Rhasspy.

**Comment by Braincoke** [comment]
Ah my bad I must have skipped something in the docs.
It worked like a charm, thanks :)
