### ISSUE TITLE
 rhasspy-tts-wavenet-hermes "missing" in debian package 2.5.9

### ISSUE THREAD

**Issue by natemason** [rhasspy/rhasspy#199]
Hi everyone,

I'm very new to rhasspy and going through my first install today I encountered an issue with using Google Wavenet TTS. When starting rhasspy with wavenet selected I would get this error in the logs:
`can't find command 'rhasspy-tts-wavenet-hermes`
The list of voices wouldn't show and I had not success with the test option in the TTS configuration.

I've installed version 2.5.9 with the arm64 debian package on a raspberry pi 3B. Everything else is functioning perfectly.

After some troubleshooting I managed to find a way around it but I'm not sure the best way to fix it properly in the code base. I found in Dockerfile.debian line 132 that the rhasspy-tts-wavenet-hermes directory is being copied in as rhasspy-wavenet-cli-hermes.
`COPY rhasspy-tts-wavenet-hermes/ ${APP_DIR}/rhasspy-wavenet-cli-hermes/`

My workaround in the existing install:

1. Create a symbolic link for rhasspy-tts-wavenet-hermes pointing to rhasspy-wavenet-cli-hermes
` cd /usr/lib/rhasspy/
ln -s rhasspy-wavenet-cli-hermes/ rhasspy-tts-wavenet-hermes`
2. Install the missing google package dependency for wavenet
`cd /usr/lib/rhasspy/usr/local/lib/
bin/python3.7 -m pip install google-cloud-texttospeech==2.0.0
`
3. Restart rhasspy and tested as working.

Thanks,
Nathan

**Comment by synesthesiam** [comment]
Hopefully fixed with 2.5.10. Please comment if the issue persists.
