### ISSUE TITLE
Missing available STT systems in docs

### ISSUE THREAD

**Issue by cyaelcastro** [rhasspy/rhasspy#201]
In the [online docs](https://rhasspy.readthedocs.io/en/latest/speech-to-text/) are missing available languages in STT section. The missing ones:

Kaldi: Italian, Spanish, Russian
Deepspeech: French, Spanish, Italian

![image](https://user-images.githubusercontent.com/37314063/111260601-bfb1b980-85e6-11eb-86fc-2a5356eece05.png)

![image](https://user-images.githubusercontent.com/37314063/111260697-e96ae080-85e6-11eb-9a9d-7f5f523bad25.png)

![image](https://user-images.githubusercontent.com/37314063/111260792-10291700-85e7-11eb-8d0a-759df93faa6d.png)

**Comment by synesthesiam** [comment]
Thanks! I'm updating this now :+1:
