### ISSUE TITLE
Wavenet missing google.cloud module

### ISSUE THREAD

**Issue by synesthesiam** [rhasspy/rhasspy#208]
2.5.10 Wavenet will not function with missing module

**Comment by h4de5** [comment]
is there a way to manually/temporaly patch an existing docker installation? I tried to add the package to 
`/usr/lib/rhasspy/rhasspy-tts-wavenet-hermes/requirements.txt` but it did not help.

**Comment by synesthesiam** [comment]
Should be fixed now in latest 2.5.10
