### ISSUE TITLE
/api/text-to-speech crash audio

### ISSUE THREAD

**Issue by mkcologne** [rhasspy/rhasspy#210]
If I send a string to the api (with nodered), the audio chrashes. 
No Beeps no tts from the webui anymore.
tts throws errormessage: 

`AudioServerException: Command '['aplay', '-q', '-t', 'wav', '-D', 'default:CARD=I82801BAICH2']' returned non-zero exit status 1.`

log:

`[ERROR:2021-04-06 09:16:58,411] rhasspyserver_hermes: Command '['aplay', '-q', '-t', 'wav', '-D', 'default:CARD=I82801BAICH2']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1700, in api_text_to_speech
    results = await asyncio.gather(*aws)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1686, in speak
    volume=volume,
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 614, in speak_sentence
    raise AudioServerException(play_response.error)
rhasspyserver_hermes.AudioServerException: Command '['aplay', '-q', '-t', 'wav', '-D', 'default:CARD=I82801BAICH2']' returned non-zero exit status 1.
[ERROR:2021-04-06 09:16:58,411] rhasspyserver_hermes: AudioPlayError(error="Command '['aplay', '-q', '-t', 'wav', '-D', 'default:CARD=I82801BAICH2']' returned non-zero exit status 1.", site_id='default', context='05b57414-c983-4214-8a76-f683951882d6', session_id='05b57414-c983-4214-8a76-f683951882d6')
[DEBUG:2021-04-06 09:16:58,410] rhasspyserver_hermes: Handling TtsSayFinished (topic=hermes/tts/sayFinished, id=abebd4fe-4b3b-432c-862e-76464306ff4f)
[DEBUG:2021-04-06 09:16:58,366] rhasspyserver_hermes: Handling AudioPlayError (topic=hermes/error/audioServer/play, id=abebd4fe-4b3b-432c-862e-76464306ff4f)
[DEBUG:2021-04-06 09:16:58,354] rhasspyserver_hermes: Handling AudioPlayBytes (topic=hermes/audioServer/default/playBytes/05b57414-c983-4214-8a76-f683951882d6, id=abebd4fe-4b3b-432c-862e-76464306ff4f)
[DEBUG:2021-04-06 09:16:58,286] rhasspyserver_hermes: Publishing 174 bytes(s) to hermes/tts/say
[DEBUG:2021-04-06 09:16:58,286] rhasspyserver_hermes: -> TtsSay(text='Welcome to the world of offline voice assistants.', site_id='default', lang=None, id='05b57414-c983-4214-8a76-f683951882d6', session_id='', volume=1.0)`

**Comment by synesthesiam** [comment]
Are you able to play audio from the command-line with that device id (`default:CARD=I82801BAICH2`)?

**Comment by mkcologne** [comment]
Yes I did. After further insvestigation and on a new build on Raspian with Rhasspy on docker and nodered local the problem exist no more. Also figured out, that the latest nodered AudioOut-Node seems to be a bit buggy. U can close this Issue!
Cheers-Michael
