### ISSUE TITLE
MQTT port missing in profile.json

### ISSUE THREAD

**Issue by urbatecte** [rhasspy/rhasspy#213]
Hi,

I open this issue due to a unintended breaking change in the last version of HLC (HermesLedControl) : https://github.com/project-alice-assistant/HermesLedControl/issues/100
It's a great piece of code from @Psychokiller1888  to benefit of the LEDs on several board.

HLC last version change the MQTT port to reflect the one use by Rhasspy internal brocker (ie 12183).
To make configuration easy, HLC already get the MQTT external host in the profile.json, but... it may find also the MQTT port to be consistent.
Unfortunatly the MQTT port seems to be missing in the profile.json (whereas it's depicted in https://rhasspy.readthedocs.io/en/latest/reference/#profile-settings  :-)

Maybe a nice enhancement/fix to be considered.
Thanks

**Comment by renarena** [comment]
I had to search a lot to find out why HLC was not working - the missing port...

**Comment by donburch888** [comment]
Rhasspy's web interface **displays** the default port number, but does not save it to profile.json **unless it is changed**. Rhasspy can use port 1883 or 12183 for MQTT depending on whether it's Internal or External, or whether Docker is used.  

While Rhasspy works this out correctly, HLC sometimes guesses wrong. 

It would make sense for MQTT port to explicitly be written to profile.json ... but it's also not hard to add it in the Advanced menu, as long as we tell people.

**Comment by synesthesiam** [comment]
Rhasspy writes the settings that are different from [defaults.json](https://github.com/rhasspy/rhasspy-profile/blob/master/rhasspyprofile/profiles/defaults.json) to the profile. The reasoning is that it lets me change the defaults over time (to get better performance, etc.) while allowing Rhasspy to keep the settings people have purposefully changed. The logic for this is all in [rhasspy-profile](https://github.com/rhasspy/rhasspy-profile/blob/master/rhasspyprofile/profile.py).

You can use the [`/api/profile`](https://rhasspy.readthedocs.io/en/latest/reference/#api_profile) HTTP endpoint to get a complete profile with all of the settings.

**Comment by Romkabouter** [comment]
Expected behaviour :)
