### ISSUE TITLE
error in file size in larynx download 

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#214]
when activating larynx Rhasspy asks to download additional files and I have a size error:

rhasspyprofile.download.DownloadFailedException: ('https://github.com/rhasspy/gruut/releases/download/v0.9.0/fr-fr.tar.gz', 'File size mismatch (got 9991077 byte(s), expected 9983999)')

modif:
/usr/lib/rhasspy/rhasspy-profile/rhasspyprofile/profiles/fr/profile.json
line 682        "bytes_expected":    9983999    -> to :      "bytes_expected": 9991077

**Comment by synesthesiam** [comment]
Fixed in `master`
