### ISSUE TITLE
Download files for Larynx

### ISSUE THREAD

**Issue by Teschi2494** [rhasspy/rhasspy#219]
When trying to download the missing files for Larynx TTS, the following error occurs:

ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:<ssl.SSLContext object at 0xaee3f7b0> [Temporary failure in name resolution]

Its about the following files:
![image](https://user-images.githubusercontent.com/82723670/116845212-80b2e400-abe5-11eb-9e69-fb43f3f48d89.png)

Is there a solution or workaround to download Larynx TTS?

**Comment by synesthesiam** [comment]
I'm assuming this was just a problem at that point with Github. Let me know if this is still a problem.
