### ISSUE TITLE
Unable to add the custom words

### ISSUE THREAD

**Issue by manju-rn** [rhasspy/rhasspy#22]
2 issues:
1. When i guess a new word and try adding it through "Save Custom words", it does not add to the block below
2.  When I manually add the words and pronunciation as provided by the "Guess word", I get below errors.   I have tried adding a custom wake words, and I suspect due to below it gives wake word "xxx" not found in the dictionary

Command 'fstcompile --keep_isymbols --keep_osymbols --isymbols=/tmp/tmpynenbyw9/isymbols.txt --osymbols=/tmp/tmpynenbyw9/osymbols.txt /tmp/tmpynenbyw9/graph.fst.txt "/tmp/tmpynenbyw9/graph.fst.fst"' returned non-zero exit status 127.

Also, here are the screenshots of 2.5 Pre version where there is no option to directly add the words like it is possible in 2.4.19.  Even though the words can be "pronounced", they need to be manually added

![image](https://user-images.githubusercontent.com/26291847/78841077-09853d80-7a2f-11ea-86b1-6e01b7b80503.png)

**Comment by snail59** [comment]
Hello,

error code 127 means "command not found". I had the same problem and manually installed the package. Then, I got the same error with ngramcount command, so installed it too.

If using a debian derivated operating system, the command is 
`apt install libfst-tools libngram-tools`

That should solve your problem.

If you want to find which package provides a command or a file, you can use this website : [https://command-not-found.com](https://command-not-found.com)
