### ISSUE TITLE
Running command for intent handling produces FileNotFoundError

### ISSUE THREAD

**Issue by evanlaf** [rhasspy/rhasspy#223]
Hi, 

I am running Rhasspy on a web interface on Ubuntu 20.04. I am trying to run a local command for intent handling from Rhasspy. I customized my profile to reflect my program:
```
"handle": {
        "system": "command",
        "command": {
            "program": "/home/evl/.config/rhasspy/profiles/en/rhasspy-win/main.py"
        }
    },
```

As you can see, and by [this issue](https://github.com/rhasspy/rhasspy/issues/50), I used an absolute path. Rhasspy logs don't show anything of importance, but Docker logs show this:
```
[DEBUG:2021-05-24 11:30:19,753] rhasspyserver_hermes: Handling NluIntent (topic=hermes/intent/GetTime, id=58fb283d-cedc-4da4-80ae-3dfc1b9358e1)
[DEBUG:2021-05-24 11:30:19,754] rhasspyremote_http_hermes: ['/home/evl/.config/rhasspy/profiles/en/rhasspy-win/main.py']
[ERROR:2021-05-24 11:30:19,768] rhasspyremote_http_hermes: handle_intent
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-remote-http-hermes/rhasspyremote_http_hermes/__init__.py", line 824, in handle_intent
    stderr=asyncio.subprocess.PIPE,
  File "/usr/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1533, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/evl/.config/rhasspy/profiles/en/rhasspy-win/main.py': '/home/evl/.config/rhasspy/profiles/en/rhasspy-win/main.py'
[DEBUG:2021-05-24 11:30:19,758] rhasspyserver_hermes: Sent 370 char(s) to websocket
```

As you can see, it's looking for the file main.py which does not exist. I am 100% sure that the path is correct because I copied and pasted `pwd` output. Does anyone have any ideas as to how to fix this? 

I previously tried using asyncio and websockets myself, but couldn't run any asynchronous methods while the websocket ran forever, so I'm now trying to run it as a program. Any help would be appreciated. Thanks!

**Comment by Romkabouter** [comment]
Inside docker, the path "/home/evl/.config/rhasspy/profiles/en/rhasspy-win/main.py" does not exist.
It only exist on the host.
Changing the path to /profiles/en/rhasspy-win/main.py will work, because that is path is available in the container.
It is mapped to the profiles folder for Rhasspy on the host: /home/evl/.config/rhasspy/profiles/en I assume in your case

The issue you mention is different, because the variable ${RHASSPY_PROFILE_DIR} was not working. Normally, that would be filled with /profile/en/.
That issue is fixed so it seems so can also use: ${RHASSPY_PROFILE_DIR}/rhasspy-win/main.py

**Comment by evanlaf** [comment]
@Romkabouter Thanks for the clarification, I'm sure this will definitely help! I figured another way around this issue, and just forgot to close this. I'll check out this fix later and see if it works.
