### ISSUE TITLE
Set siteID via Docker command

### ISSUE THREAD

**Issue by prabbit237** [rhasspy/rhasspy#224]
I am setting up some Pi Zero's that use a command in the rc.local to set the hostname automatically based off the serial #. To wit:

````
echo zero-`grep Serial /proc/cpuinfo|cut -b 19-`>/etc/hostname
````
I'm doing that so I can setup one device, copy the SD card back to an image and then use it on several devices. Might not be the best way to do it and it actually takes two reboots to set, due to using rc.local, but it works.

But it'd be nice if there was some way to set the siteID on the docker command such as "... -e siteID=$HOSTNAME..." (or whatever other criteria may be desired.) That way I can make an image and copy it to several satellite setups and they'd be "plaug-and-play."

If this already exists, I wasn't able to locate it in the docs.

**Comment by synesthesiam** [comment]
It's possible, but definitely not obvious!

At the end of your Docker command, you usually pass a profile like:

```sh
docker run ... -p en
```

You can actually pass additional arguments after a `--` to the [Rhasspy web server](https://github.com/rhasspy/rhasspy-server-hermes) like this:

```sh
docker run ... -p en -- more arguments here
```

One of those arguments is `--set <key> <value>`, which lets you override a profile setting. The one you're interested in is `mqtt.site_id`. So putting it all together:

```sh
docker run ... -p en -- --set mqtt.site_id "my_cool_site_id"
```

**Comment by prabbit237** [comment]
Ah, OK. I was hoping not to have to resort to only HTTP access to the main server. Thanx (and it shows it wasn't that oddball of a request, since it'd already occurred to someone to come up with the solution. I hate thinking at times that I'm the only one who wants a specific feature.)
