### ISSUE TITLE
Feature/Support setting tag to a optional word

### ISSUE THREAD

**Issue by fugitive90** [rhasspy/rhasspy#226]
Say we have sample sentence like this: 
[GetWiki]
what is []{name}

If we speak `what is car`, car would be tagged with {name} , or if we speak `what is a dolar` , dolar would be tagged as {name}, which we could use for latter processing. I am aware of making rules or slot list, but my point is how we can make rhasspy recognize that 'optional' word.

**Comment by Romkabouter** [comment]
Have a look at https://rhasspy.readthedocs.io/en/latest/training/#language-model-mixing, it might be what you are after.
