### ISSUE TITLE
FstCompiler: Symbol is not mapped to any integer arc ilabel

### ISSUE THREAD

**Issue by Whogives23** [rhasspy/rhasspy#227]
I am trying to integrate the homeassistant examples files into my hassio rhasspy addon. I have copied the files '/examples/homeassistant/profile' into '/shares/rhasspy/profiles/en', and after a reboot of the service, these changes are all pulling through to the rhasspy UI.

However, when training on the new sentences/words, the following below error occurs. Having a look at the language_model.txt at the stated line, I can see its failing on an unknown entity: _421 493 - - 0.0_

This also occurs if an entity name has an _ in it: _183 296 kitchen_downlights kitchen_downlights 0.0_

> FATAL: FstCompiler: Symbol "-" is not mapped to any integer arc ilabel, symbol table = /share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt, source = /share/rhasspy/profiles/en/kaldi/language_model.txt, line = 547
[ERROR:2021-06-08 21:52:30,798] rhasspyasr_kaldi_hermes: train
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-asr-kaldi-hermes/rhasspyasr_kaldi_hermes/__init__.py", line 618, in handle_train
    spn_phone=self.spn_phone,
  File "/usr/lib/rhasspy/rhasspy-asr-kaldi/rhasspyasr_kaldi/train.py", line 163, in train
    language_model_type=language_model_type,
  File "/usr/lib/rhasspy/rhasspy-asr-kaldi/rhasspyasr_kaldi/train.py", line 342, in train_kaldi
    subprocess.check_call(compile_grammar, cwd=model_dir, env=extended_env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['fstcompile', '--isymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/share/rhasspy/profiles/en/kaldi/language_model.txt', '/share/rhasspy/profiles/en/kaldi/model/data/lang/G.fst']' returned non-zero exit status 1.
[DEBUG:2021-06-08 21:52:30,801] rhasspyasr_kaldi_hermes: -> AsrError(error="Command '['fstcompile', '--isymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/share/rhasspy/profiles/en/kaldi/language_model.txt', '/share/rhasspy/profiles/en/kaldi/model/data/lang/G.fst']' returned non-zero exit status 1.", site_id='default', context=None, session_id='0970bdf4-456c-4d8b-970f-6897e39e81f3')
[DEBUG:2021-06-08 21:52:30,801] rhasspyasr_kaldi_hermes: Publishing 470 bytes(s) to hermes/error/asr
[DEBUG:2021-06-08 21:52:30,877] rhasspyserver_hermes: Handling AsrError (topic=hermes/error/asr, id=02c02a90-0533-4e8d-a582-7fd448a148d0)
[ERROR:2021-06-08 21:52:30,879] rhasspyserver_hermes: AsrError(error="Command '['fstcompile', '--isymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/share/rhasspy/profiles/en/kaldi/language_model.txt', '/share/rhasspy/profiles/en/kaldi/model/data/lang/G.fst']' returned non-zero exit status 1.", site_id='default', context=None, session_id='0970bdf4-456c-4d8b-970f-6897e39e81f3')
[ERROR:2021-06-08 21:52:30,880] rhasspyserver_hermes: Command '['fstcompile', '--isymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/share/rhasspy/profiles/en/kaldi/language_model.txt', '/share/rhasspy/profiles/en/kaldi/model/data/lang/G.fst']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 1306, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy/rhasspy-server-hermes/rhasspyserver_hermes/__init__.py", line 471, in train
    raise TrainingFailedException(reason=asr_response.error)
rhasspyserver_hermes.TrainingFailedException: Command '['fstcompile', '--isymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--osymbols=/share/rhasspy/profiles/en/kaldi/model/data/lang/words.txt', '--keep_isymbols=false', '--keep_osymbols=false', '/share/rhasspy/profiles/en/kaldi/language_model.txt', '/share/rhasspy/profiles/en/kaldi/model/data/lang/G.fst']' returned non-zero exit status 1.

Any help or direction would be appreciated

**Comment by synesthesiam** [comment]
What do your "friendly" entity names look like? If they have dashes and underscores in them, I could see this causing a problem. In the example, I was assuming they would be something like "Kitchen Light".

**Comment by Whogives23** [comment]
Hi. I used hyphens in my my automations as a type of naming convention:
Auto Lights - Kitchen - Nighttime
Auto Lights - Diningroom - Brightness

I had some switch entities that were named with underscores as well.

The 'Solution' to this is to rename these entities(of which I have 800+ in total). It's been a task. But I am operational. Thanks.

**Comment by synesthesiam** [comment]
OK, glad you found a solution. I wonder if it would be possible to strip out some of these characters in the slot program. As long as the entity id is not changed, I would expect it to still work.

**Comment by Whogives23** [comment]
This seems to be how Home Assistant handles it(except scripts that throw an error on save)
name: Retain Switch - Study
Entity_id: retain_switch_study
