### ISSUE TITLE
% in MQTT password crashes Rhasspy

### ISSUE THREAD

**Issue by andreasbrett** [rhasspy/rhasspy#228]
Providing an external MQTT login password produces errors and crashes Rhasspy. I particularly had issues with "%".

Here's the error. Building the supervisord.conf file might require escaping "%" to work. Note: For sharing this I anonymized the password of course to "***%***".

Error: Format string "rhasspy-microphone-cli-hermes --sample-rate 16000 --sample-width 2 --channels 1 --record-command 'arecord -q -r 16000 -f S16_LE -c 1 -t raw -D sysdefault:CARD=USB' --list-command 'arecord -L' --test-command 'arecord -q -D {} -r 16000 -f S16_LE -c 1 -t raw' --debug --host example.com --port 8883 --site-id default --username rhasspy --password '***%***' --tls --tls-cert-reqs CERT_REQUIRED --tls-version 2 --udp-audio-host 127.0.0.1 --udp-audio-port 12202" for 'program:microphone.command' is badly formatted: unsupported format character ''' (0x27) at index 380 in section 'program:microphone' (file: '/profiles/de/supervisord.conf')

**Comment by Romkabouter** [comment]
This seems to be more a problem of MQTT (you can find a lot of posts in Google about this), then a Rhasspy error.
