### ISSUE TITLE
Speech To Text - Remote HTTP problem

### ISSUE THREAD

**Issue by ChrisB85** [rhasspy/rhasspy#229]
Hi,

I have connected my Snips Satellite with Rharppy instance, but I have problem with Speech To Text - Remote HTTP component. As SST I'm using DeepSpeech server [https://hub.docker.com/r/romainsah/deepspeech-server/](https://hub.docker.com/r/romainsah/deepspeech-server/) which is based on [https://github.com/MainRo/deepspeech-server](https://github.com/MainRo/deepspeech-server). It converts my speech to text properly (as i see it in DeepSpeech server log) and returns it as plain text, but SST throws error:

`[ERROR:2021-06-15 18:54:03,800] rhasspyremote_http_hermes: handle_stop_listening
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-remote-http-hermes/rhasspyremote_http_hermes/__init__.py", line 606, in handle_stop_listening
    transcription_dict = await response.json()
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://192.168.0.6:7123/stt?siteId=kitchen')`

Same thing in MQTT:
`{"error": "0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://192.168.0.6:7123/stt?siteId=kitchen')", "siteId": "kitchen", "context": "url='http://192.168.0.6:7123/stt', command='None'", "sessionId": "kitchen-default-cb1a95ad-1c00-49f2-bb16-af76b066df8e"}`

Full log is [here.](https://pastebin.com/0McddqNw)

As I see the problem is that DeepSpeech server responses with application/octet-stream mimetype header. Can that be fixed on SST module-side by ignoring mimetype header?

**Comment by synesthesiam** [comment]
This should be fixable on the Rhasspy side, The relevant code is here: https://github.com/rhasspy/rhasspy-remote-http-hermes/blob/5184f86079961507e8d19fb06d0b56dd9a5b0dcb/rhasspyremote_http_hermes/__init__.py#L598

Another option might be to use the "Local Command" option for STT. It takes WAV audio on stdin and is expected to just return plain text. So you could just use `curl` for the program and for the arguments: `-X POST --data-binary - --output -`

**Comment by ChrisB85** [comment]
Thanks, 

I was able to create my own DeepSpeech server with nodejs: https://github.com/ChrisB85/rhasspy-remote-http-server
I think there is a mistake in docs, because it tells that mimetype should be `text/plain`
https://rhasspy.readthedocs.io/en/latest/speech-to-text/#remote-http-server
