### ISSUE TITLE
Submodules init problem

### ISSUE THREAD

**Issue by ChrisB85** [rhasspy/rhasspy#230]
Hi,

I have a problem with submodules initialisation:

`Submodule path 'rhasspy-asr-kaldi': checked out '191abb747f2aca7de75e9cc7ebc5ef4e57198531'
fatal: remote error: upload-pack: not our ref 08445f377c654ac102756208dc1b6a7cb3bff92e
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'rhasspy-asr-kaldi-hermes', but it did not contain 08445f377c654ac102756208dc1b6a7cb3bff92e. Direct fetching of that commit failed.`

It looks like there are some unpushed changes :)

**Comment by synesthesiam** [comment]
Hopefully all up to date now :)
