### ISSUE TITLE
picoTTS - voice en-GB

### ISSUE THREAD

**Issue by DandyDiamond** [rhasspy/rhasspy#26]
Hi trivial I know...

Trying to use the en-GB voice in picoTTS but get a female American voice.  Settings look correct.
Pi 3B+, Buster, Rhasspy installed using Docker.

    "text_to_speech": {
        "disable_wake": true,
        "picotts": {
            "language": "en_GB"
        },
        "system": "picotts",
        "wavenet": {
            "samplerate": 22050
        }
    },

Keep up the good work!

**Comment by synesthesiam** [comment]
Should be fixed finally. Please re-open if there are still problems.
