### ISSUE TITLE
snowboy is dead; any way to pull from old image?

### ISSUE THREAD

**Issue by tulth** [rhasspy/rhasspy#261]
https://snowboy.kitt.ai/ seems like it is down now :(

I really liked the snowboy wake word capability.  Any suggestions on how I could migrate snowboy from one machine to another?  It appears the data is not stored in the profile.

I could only find some of the files on the container image, here:
```
./usr/lib/rhasspy/.venv/lib/python3.7/site-packages/snowboy/resources/models/jarvis.umdl
./usr/lib/rhasspy/rhasspy-wake-snowboy-hermes/rhasspywake_snowboy_hermes/models/jarvis.umdl
```

**Comment by ableischwitz** [comment]
You may want to take a look at the github-repo if you are looking for the umdl files - not sure if that would be sufficient.
[https://github.com/Kitt-AI/snowboy/tree/master/resources/models](https://github.com/Kitt-AI/snowboy/tree/master/resources/models)

**Comment by synesthesiam** [comment]
Also check out: https://github.com/rhasspy/snowboy-seasalt

You can train your own wake word offline!
