### ISSUE TITLE
Bug Matrixvoice speaker rhasspy speak

### ISSUE THREAD

**Issue by nicoxygen** [rhasspy/rhasspy#27]
Speaker on matrix voice and rhasspy is good configured when i work on wake word i have sound beep_... . wav, but when i want to use tts with picotts or espeak i have an error:

AudioServerException: Command '['aplay', '-q', '-t', 'wav', '-D', 'hw:CARD=MATRIXIOSOUND,DEV=1']' returned non-zero exit status 1.

Pi 3B+, Buster, Rhasspy installed using Docker.

**Comment by Romkabouter** [comment]
Is this stil an issue on the latest release?

**Comment by Romkabouter** [comment]
@nicoxygen bump :)
