### ISSUE TITLE
Rhasspy doesn’t send events automatically after recognition

### ISSUE THREAD

**Issue by jonalbr** [rhasspy/rhasspy#288]
Hi,

I can speak my sentence and the intent/event is recognized as defined. However the event (I use events) won’t be sent to home assistant. If I now press “recognize” while “handle” is checked and the sentence is still typed in, the event was sent to home assistant without a problem. 

So my setup works perfectly when using the “recognize” button, but not without. 

Has someone a similar problem and guide me in the right direction towards the solution?

I use a master + satellite configuration which worked as intended apart from the ‘small’ problem described above. 

Thanks a lot in advanced.

**Comment by donburch888** [comment]
Sounds like the satellite is not passing control to the master machine correctly.  

How is the "Intent Handling" section of Rhasspy on your satellite machine set up ?  Have you created and using a HA Long-lived access token ?

Can you post the profiles of both your satellite and master rhasspys.  Copy from the "Advanced" option and paste into code segments (using the  "< >" button when writing your post here
![image](https://user-images.githubusercontent.com/60803198/202829736-e6470f48-acca-43cb-a9b6-6d85d1b32274.png)
