### ISSUE TITLE
Wildcards in sentences

### ISSUE THREAD

**Issue by maxnatamo** [rhasspy/rhasspy#297]
Is there any plans to add wildcards to the sentence-parser? I.e.
```ini
[AddToShoppingList]
add (*){item} to shopping list
```
would match anything in the 'item'-field.

I'm aware that this is beyond the JSGF-specitification and most likely not supported by whatever library handles it. However, this would make situations like this much more approachable, as opposed to having an enormous slots-file. Even slot-programs using dictionaries have issues, when handling plural items (e.g. egg vs eggs).

**Comment by jonnieey** [comment]
Also was tring to implement a simple math intent
```
[DoMath]
operators = ($hass/math) {operator}
nums = (0..999)
<nums>{num1} <operators> <nums>{num2}
```
I tried to use `(0..99999999)` but it's too large. Also it doesn't work for decimal eg "fifty point one"
