### ISSUE TITLE
Pocketsphinx: No language model is written, even if Rhasspy is trained

### ISSUE THREAD

**Issue by Pittermaennchen** [rhasspy/rhasspy#3]
My setup:
Raspberry Pi 4 running Raspbian Buster
Rhasspy: pre-pre Version of Rhasppy 2.5
profile: german (de)

**My problem:**
I would like to use pocketsphinx for Speech to Text. But when I hit the Train-button after adding my intents and sentences to sentences.ini, **no language_model.txt-file is written to my profile.**
Instead I get the error-message: "name 'language_model' is not defined"

Therefore, Rhasspy does not translate my speech commands to text.

**Comment by synesthesiam** [comment]
Should hopefully be fixed now :)
