### ISSUE TITLE
siteid missing

### ISSUE THREAD

**Issue by ulno** [rhasspy/rhasspy#30]
Just tried to make a demonstration video for rhasspy 2.5 in venv and got stuck.
The latest version doesn't emit a site id in the json on the websocket /api/events/intent anymore - I though see the id in the console log.

This breaks a lot of setups. Any possibility to get this back?

**Comment by synesthesiam** [comment]
A fix is in the pipeline now. Sorry about that! Further discussion: https://github.com/rhasspy/rhasspy-voltron/issues/31
