### ISSUE TITLE
WebSocket API doesn't catch intents on base, only on satellite

### ISSUE THREAD

**Issue by koenvervloesem** [rhasspy/rhasspy#31]
I have this Node-RED flow [gettime-flow.json](https://gist.github.com/koenvervloesem/b76bbdbc2cd77c35760c145c2f710f25) to handle the GetTime intent.

Last time I tried this flow, this was with a basic setup of one Rhasspy machine and this worked: it could recognize the GetTime intent and reply.

Now  I'm testing the same flow on a base/satellite MQTT setup:
- Base: no audio, intent recognition enabled
- Satellite: audio, Hermes MQTT to communicate with the base

If I enter the master's WebSocket URL in the websocket in node and I talk to the satellite, the websocket in node doesn't get the recognized intents. Only if I use the satellite's WebSocket URL and talk to the satellite, the recognized intents are coming in.

Of course for this to work I also need the siteID, which is missing (see https://github.com/rhasspy/rhasspy-voltron/issues/30), but this flow doesn't even get the recognized intent.

**Comment by synesthesiam** [comment]
Pushing a new Docker image with a fix for the missing siteId. Added in the sessionId, customData, and wakewordId for good measure.

The master/satellite issue needs some more thought. The easy fix is to have the master web server automatically listen for siteIds from all satellites. Is there ever a case where a user would not want to do this?

**Comment by koenvervloesem** [comment]
I'm not sure about all possible cases (Rhasspy allows a lot ;-)), but the most common case seems to be that the master does intent recognition and the satellites are just audio receivers and players with wake word recognition. So at least for that case, I would expect that listening to the `ws://rhasspy:12101/api/events/intent` WebSocket URL on the master will also get me the intents originating from sentences spoken on the satellites.

I can't find a case where this behaviour is not wanted. But maybe I'm thinking about this with my MQTT hat on, which I'm much more accustomed to than WebSockets. Maybe @ulno has more experience with this?

**Comment by synesthesiam** [comment]
I'll plan to add it in for now. We just need to be extra careful about which messages the master web server responds to. Me forgetting small things tends to lead to some service duplicating a response :/

**Comment by ulno** [comment]
tried a new version today in venv and still had no siteId - i am now using change nodes in Node-Red and remember the siteid myself based on teh websocket I am listening to.

**Comment by synesthesiam** [comment]
I got this working this morning for the wake/text/intent websocket messages. The base station will now check the satellite site ids for the respective wake/ASR/NLU system and forward those events to the base websocket clients.

This seems to be a problem only with MQTT base/satellite set ups. Using remote HTTP works because the base handles all the requests as if they were its own.

**Comment by synesthesiam** [comment]
Should be in the main Docker image now.
