### ISSUE TITLE
Old Linux is only option? libgfortran4 missing issue

### ISSUE THREAD

**Issue by Hunanbean-Collective** [rhasspy/rhasspy#322]
I cannot seem to get libgfortran4 on Linux Mint, which it says is a dependency, and it will not install without it. 
My only guess is that i need to fallback a version or two. This just does not seem right. 
Any help is appreciated

**Comment by fluidvoice** [comment]
see >> https://github.com/rhasspy/rhasspy/issues/317#issue-1577112528
and use  of libfortran5

**Comment by Hunanbean-Collective** [comment]
Great, thank you!

I do intend to use deepspeech, so i will stop at the point right before that for now and do a but more research. (But i am sure that will fix that particular issue)
This is being done in a VM. I already have deepspeech with CUDA setup in a conda env on the host, so ideally, i would somehow use that.

**Comment by DivanX10** [comment]
The thing is that libgfortran4 is designed for Debian 10.2 and rhasspy 2.5.11 was built on Debian 10.2, so you cannot install rhasspy, getting a message that libgfortran4 does not have a package or there is a newer version. How to fix it?

1) Installing Rhasspy Assistant on Debian 11.6

```
mkdir /home/rhasspy
```
```
cd /home/rhasspy
```
```
wget https://github.com/rhasspy/rhasspy/releases/latest/download/rhasspy_amd64.deb
```
```
dpkg-deb --extract rhasspy_amd64.deb tmp
```
```
dpkg-deb --control rhasspy_amd64.deb tmp/DEBIAN
```
2) Open /home/rhasspy/tmp/DEBIAN/control, find libgfortran4 and edit to libgfortran5
or edit with the command
```
sed -i 's/\libgfortran4\b/libgfortran5/g' /home/rhasspy/tmp/DEBIAN/control
```

3) Building the package rhasspy_amd64.deb
```
sudo dpkg --build tmp rhasspy_amd64.deb
```

4) Launching the rhasspy installation
```
sudo dpkg -i ./rhasspy_amd64.deb
```

5) Putting a mosquito
```
sudo apt install -y mosquitto
```

> If errors occur when installing packages
>```
>apt --fix-broken install
>```

6) Creating a config for mosquitto.conf
```
sudo nano /etc/mosquitto/conf.d/mosquitto.conf
```

7) Adding to mosquitto.conf
```
listener 1883
allow_anonymous true
```

8) Launching the mosquito
```
sudo systemctl is-enabled mosquitto
```

9) Checking the status of the mosquito
```
sudo systemctl status mosquitto
```

10) To check, run rhasspy through the console
```
PATH="$PATH:/usr/sbin" rhasspy --profile ru
```

**Comment by Hunanbean-Collective** [comment]
Great! Thanks for the detailed breakdown. Between the two methods, it should be ok to close the issue. I will rename it to include libgfortran4 in the title, to make it easier to find.

**Comment by evias** [comment]
If you are looking at this a few years on, you will need 2 more fixes:

- `libopenblas-base` dependency must be changed for `libopenblas0`.
- adding `libssl1.1` as it is used as a shared library in rhasspy but libssl3 installed with latest OS.

```bash
sudo apt install libssl1.1
sed -i 's/\libopenblas-base\b/libopenblas0/g' /home/rhasspy/tmp/DEBIAN/control
```

Thanks for this fix!
