### ISSUE TITLE
optional word at start of sentence breaks intent recognition

### ISSUE THREAD

**Issue by stuffinator** [rhasspy/rhasspy#324]
According to the docs at https://rhasspy.readthedocs.io/en/latest/training/#optional-words it should be possible to have an optional word at the start of the sentence. I created a template with the example provided in the docs.
```
[GetExample]
[an] example sentence [with] some optional words
```
But it complete breaks the recognition, as no variation is being recognized anymore.

![image](https://user-images.githubusercontent.com/26797810/225087337-601168dd-77c1-4cad-9b8e-a7b835db2bc6.png)
![image](https://user-images.githubusercontent.com/26797810/225087462-443954b1-01b8-4a51-81c8-3ecae9f9edc1.png)
![image](https://user-images.githubusercontent.com/26797810/225087592-3a458628-6b17-413b-993b-86d55dd80d84.png)
![image](https://user-images.githubusercontent.com/26797810/225087712-7cfd5cff-9e0d-48ed-8309-b20d8fbc3912.png)

If I put another word in front of the sentence in the template or I remove the brackets on "an", the intent is being recognized again.

```
[GetExample]
test [an] example sentence [with] some optional words
```

![image](https://user-images.githubusercontent.com/26797810/225088257-6f5cc488-bada-49d7-9cb7-948263412a05.png)
![image](https://user-images.githubusercontent.com/26797810/225088429-77471814-df6f-46dc-ad38-940223126179.png)
![image](https://user-images.githubusercontent.com/26797810/225088643-44917f5d-f66f-4e8e-b89d-1b3ec9554d06.png)
![image](https://user-images.githubusercontent.com/26797810/225088726-9c6651e4-3904-43f7-8c56-633e54b42ee2.png)

I understand the logic behind it. Starting a sentence with an optional word makes it more difficult for the parser to understand what's an intent and what is a sentence. 

However If the example sentence definition in the documentation starts with an optional word, I would've expected that to work.

**Comment by DigiNecro** [comment]
It has to be escaped. In your link you can find following:

```
Special Cases
If one of your sentences happens to start with an optional word (e.g., [the]), this can lead to a problem:

[SomeIntent]
[the] problem sentence
Python's [configparser](https://docs.python.org/3/library/configparser.html) will interpret [the] as a new section header, which will produce a new intent, grammar, etc. Rhasspy handles this special case by using a backslash escape sequence (\[):

[SomeIntent]
\[the] problem sentence
Now [the] will be properly interpreted as a sentence under [SomeIntent]. You only need to escape a [ if it's the very first character in your sentence.
```
