### ISSUE TITLE
No module named 'rhasspyasr_deepspeech'

### ISSUE THREAD

**Issue by TheLexoPlexx** [rhasspy/rhasspy#43]
I installed Rhasspy-voltron using the docker-installation method and would like to use DeepSpeech as Speech-to-Text-system. However, when restarting, I keep getting:

    28.980237596Z ModuleNotFoundError: No module named 'rhasspyasr_deepspeech'
    29.009963254Z 2020-05-20 09:57:29,009 INFO exited: speech_to_text (exit status 1; not expected)
    32.017108415Z 2020-05-20 09:57:32,016 INFO spawned: 'speech_to_text' with pid 1099
    32.434818235Z Traceback (most recent call last):
    32.434863893Z   File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    32.434878762Z     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
    32.434886849Z   File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    32.434894134Z     return _get_module_details(pkg_main_name, error)
    32.434901244Z   File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    32.434908452Z     __import__(pkg_name)
    32.434930232Z   File "/usr/lib/rhasspy-voltron/rhasspy-asr-deepspeech-hermes/rhasspyasr_deepspeech_hermes/__init__.py", line 9, in <module>
    32.434939170Z     import rhasspyasr_deepspeech
    32.434947218Z ModuleNotFoundError: No module named 'rhasspyasr_deepspeech'

And I guess this is because I am not running it inside a virtualenvironment. What would the correct procedure be?

**Comment by TheLexoPlexx** [comment]
A similar, possibly related problem also appears with the `clone-the-repo-and-build` installation method:

    ERROR: Could not find a version that satisfies the requirement rhasspy-asr-deepspeech-hermes==0.1.1 (from rhasspy==2.5.0) (from versions: none)
    ERROR: No matching distribution found for rhasspy-asr-deepspeech-hermes==0.1.1 (from rhasspy==2.5.0)

**Comment by TheLexoPlexx** [comment]
Executing `pip install rhasspy/rhasspy-asr-deepspeech` did the trick.

**Comment by patrickjane** [comment]
I have just tried to install via `venv` method, and after `make install` I get the following:

```
...
Collecting rapidfuzz==0.7.11
  Using cached https://www.piwheels.org/simple/rapidfuzz/rapidfuzz-0.7.11-cp37-cp37m-linux_armv7l.whl (612 kB)
ERROR: Could not find a version that satisfies the requirement rhasspy-asr-deepspeech-hermes==0.1.1 (from rhasspy==2.5.0) (from versions: none)
ERROR: No matching distribution found for rhasspy-asr-deepspeech-hermes==0.1.1 (from rhasspy==2.5.0)
make: *** [Makefile:144: install-rhasspy] Error 1
pi@calypso:~/rhasspy-voltron $ source .venv/bin/activate
```

Manual install as you suggested did not work:

```
(.venv) pi@calypso:~/rhasspy-voltron $ pip3 install rhasspy/rhasspy-asr-deepspeech
ERROR: Invalid requirement: 'rhasspy/rhasspy-asr-deepspeech'
Hint: It looks like a path. File 'rhasspy/rhasspy-asr-deepspeech' does not exist.
```

This was my configure:
```
./configure RHASSPY_LANGUAGE=de RHASSPY_SPEECH_SYSTEM=deepspeech
```

Any ideas?
