### ISSUE TITLE
Access to folder /rhasspy-voltron/rhasspy-snips-nlu-hermes impossible : 404

### ISSUE THREAD

**Issue by PhilippeB28** [rhasspy/rhasspy#44]
Hello, It's not possible to clone the project because the folder : /rhasspy-voltron/rhasspy-snips-nlu-hermes is not accessible and if I try to open it in github.com, i have an error 404.
Best regards

**Comment by PhilippeB28** [comment]
Hello, It's not possible to clone the project because the folder : /rhasspy-voltron/rhasspy-snips-nlu-hermes is not accessible and if I try to open it in github.com, i have an error 404.
Best regards

**Comment by synesthesiam** [comment]
Thanks for catching this. Github seems to default to private repositories now for an organization, so this accidentally got marked as private!
