### ISSUE TITLE
Home Assistant intent handling is expecting intent response in wrong format

### ISSUE THREAD

**Issue by DanielWe2** [rhasspy/rhasspy#45]
When you use Home Assistant as intent handler and set it to send intents to Home Assistant it doesn't process possible text response.

The response is processed with:
` tts_text = response_dict.get("speech", {}).get("text", "")`

But an example response form Home Assistant looks like this:
`{'card': {}, 'speech': {'plain': {'extra_data': None, 'speech': 'text to speak'}}}`

So it will never get the text from the response.

Also see: https://developers.home-assistant.io/docs/intent_firing

**Comment by synesthesiam** [comment]
Thanks! Fixed in https://github.com/rhasspy/rhasspy-homeassistant-hermes/commit/112cbb596c256c5dfeda27db0d08ee1a1197cf9d
