### ISSUE TITLE
Missing tzdata package in Docker image

### ISSUE THREAD

**Issue by tuxedo78** [rhasspy/rhasspy#48]
Hello,
Is it possible to add tzdata in the rhasspy-voltron Docker image?
That would help to pass -e TZ=xxxxx in order to have Rhasspy logs showing the right timezone.

**Comment by koenvervloesem** [comment]
You can also mount the `-v /etc/localtime:/etc/localtime:ro` volume in the container to get the timezone data of your Docker host machine.

**Comment by tuxedo78** [comment]
Indeed, it works well :)
I thought I had tested this before without success but I surely did something wrong...
Thanks koen

**Comment by koenvervloesem** [comment]
I have added this to the documentation now in the Docker and Docker Compose installation instructions.
