### ISSUE TITLE
2.5.0-pre   docker: failed to register layer: no space left on device.

### ISSUE THREAD

**Issue by jrb5665** [rhasspy/rhasspy#5]
Hi,

I tried the docker install of 2.5.0-pre.
Before attempting to install I have a 32GB partition with 24GB free and the installation gets partway through installation before filling the disk and giving the error
docker: failed to register layer: no space left on device.

How much space is required for this install?

**Comment by jrb5665** [comment]
OK, I completely removed docker and all folders it created and reinstalled docket and then rhasspy.
It appears to use approx 58GB over the OS requirements, so the 32GB indicated in the quick start guide will not be enough to install this

**Comment by jrb5665** [comment]
I blew away the container again and this time installed in a kvm VM under proxmox and it only took a few GB. Very strange

**Comment by janbrueggenjuergen** [comment]
I am having the same problems. On proxmox 7.4 i create a debian 11 container and run:

apt update && apt upgrade -y 
apt install -y curl
curl -sSL https://get.docker.com | sh
usermod -a -G docker $USER
reboot -h now

docker run -d -p 12101:12101       --name rhasspy       --restart unless-stopped       -v "$HOME/.config/rhasspy/profiles:/profiles"       -v "/etc/localtime:/etc/localtime:ro"       --device /dev/snd:/dev/snd       rhasspy/rhasspy       --user-profiles /profiles       --profile de

Even 30 GB arent enough to start the container which is very strange.
