### ISSUE TITLE
Fuzzywuzzy does not recognize intents

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy#51]
Just as the title says, if I select fuzzywuzzy it does not recognize intents. I do not get any error, just IntentNotRecognized. The same intents work fine if I change to fsticuffs instead.

System is a pi4 2gb with raspbian buster and rhasspy in a docker.

I thought about trying to train with fuzzywuzzy selected but for some strange reason I always get a timeout when I try.
`[ERROR:2020-06-06 14:58:58,219] rhasspyserver_hermes: 
Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__main__.py", line 1215, in api_train
    result = await core.train()
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__init__.py", line 395, in train
    timeout_seconds=self.training_timeout_seconds,
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__init__.py", line 898, in publish_wait
    result_awaitable, timeout=timeout_seconds
  File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[DEBUG:2020-06-06 14:49:51,563] rhasspyserver_hermes: Handling AsrTrainSuccess (topic=rhasspy/asr/pi-hime/trainSuccess, id=1fdf51f3-05b6-4d35-a44c-ed5622d3a3ca)
[DEBUG:2020-06-06 14:48:58,216] rhasspyserver_hermes: Publishing 5221 bytes(s) to rhasspy/nlu/pi-hime/train
[DEBUG:2020-06-06 14:48:58,216] rhasspyserver_hermes: -> NluTrain
[DEBUG:2020-06-06 14:48:58,209] rhasspyserver_hermes: Publishing 5221 bytes(s) to rhasspy/asr/pi-hime/train
[DEBUG:2020-06-06 14:48:58,209] rhasspyserver_hermes: -> AsrTrain
[DEBUG:2020-06-06 14:48:58,201] rhasspyserver_hermes: Subscribed to hermes/error/nlu
[DEBUG:2020-06-06 14:48:58,200] rhasspyserver_hermes: Subscribed to rhasspy/nlu/pi-hime/trainSuccess
[DEBUG:2020-06-06 14:48:58,199] rhasspyserver_hermes: Subscribed to hermes/error/asr
[DEBUG:2020-06-06 14:48:58,198] rhasspyserver_hermes: Subscribed to rhasspy/asr/pi-hime/trainSuccess
[DEBUG:2020-06-06 14:48:58,197] rhasspyserver_hermes: Finished writing /profiles/de/intent_graph.pickle.gz
[DEBUG:2020-06-06 14:48:57,455] rhasspyserver_hermes: Writing /profiles/de/intent_graph.pickle.gz
[DEBUG:2020-06-06 14:48:56,550] rhasspynlu.slots: Running program for slot rhasspy_weather_slots/named_times: ['/profiles/de/slot_programs/rhasspy_weather_slots/named_times']
[DEBUG:2020-06-06 14:48:56,437] rhasspynlu.slots: Running program for slot rhasspy/number,2,100,1: ['/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slot_programs/rhasspy/number', '2', '100', '1']
[DEBUG:2020-06-06 14:48:55,911] rhasspynlu.slots: Running program for slot rhasspy_weather_slots/temperatures: ['/profiles/de/slot_programs/rhasspy_weather_slots/temperatures']
[DEBUG:2020-06-06 14:48:55,814] rhasspynlu.slots: Running program for slot rhasspy/number,0,59,1: ['/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slot_programs/rhasspy/number', '0', '59', '1']
[DEBUG:2020-06-06 14:48:55,285] rhasspynlu.slots: Running program for slot rhasspy_weather_slots/items: ['/profiles/de/slot_programs/rhasspy_weather_slots/items']
[DEBUG:2020-06-06 14:48:55,171] rhasspynlu.slots: Running program for slot rhasspy/number,0,31,1: ['/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slot_programs/rhasspy/number', '0', '31', '1']
[DEBUG:2020-06-06 14:48:55,169] rhasspynlu.slots: Loading slot rhasspy/days from /usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slots/rhasspy/days
[DEBUG:2020-06-06 14:48:55,068] rhasspynlu.slots: Running program for slot rhasspy/number,0,24,1: ['/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slot_programs/rhasspy/number', '0', '24', '1']
[DEBUG:2020-06-06 14:48:54,964] rhasspynlu.slots: Running program for slot rhasspy/number,0,7,1: ['/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slot_programs/rhasspy/number', '0', '7', '1']
[DEBUG:2020-06-06 14:48:54,354] rhasspynlu.slots: Running program for slot rhasspy_weather_slots/named_days: ['/profiles/de/slot_programs/rhasspy_weather_slots/named_days']
[DEBUG:2020-06-06 14:48:54,352] rhasspynlu.slots: Loading slot state_on_off from /profiles/de/slots/state_on_off
[DEBUG:2020-06-06 14:48:53,794] rhasspynlu.slots: Running program for slot rhasspy_weather_slots/conditions: ['/profiles/de/slot_programs/rhasspy_weather_slots/conditions']
[DEBUG:2020-06-06 14:48:53,793] rhasspynlu.slots: Loading slot rhasspy/months from /usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/profiles/de/slots/rhasspy/months
[DEBUG:2020-06-06 14:48:53,792] rhasspynlu.slots: Loading slot lights from /profiles/de/slots/lights
[DEBUG:2020-06-06 14:48:53,773] rhasspynlu.ini_jsgf: Loaded ini file
[DEBUG:2020-06-06 14:48:53,770] rhasspyserver_hermes: Generating intent graph
[DEBUG:2020-06-06 14:48:53,768] rhasspyserver_hermes: Loading sentences from [PosixPath('/profiles/de/sentences.ini')]
[INFO:2020-06-06 14:48:53,766] rhasspyserver_hermes: Starting training`

As soon as I switch back to fsticuffs training works again. 

Daenara

**Comment by synesthesiam** [comment]
The fuzzywuzzy backend has to generate all possible sentences during training, which is very expensive for even moderate numbers of sentences or slot values (1000's).

Rhasspy should time out after automatically 10 minutes of training. I need to add an option to extend this.
