### ISSUE TITLE
[Feature Request] Bring back confirmation for training and restart

### ISSUE THREAD

**Issue by Daenara** [rhasspy/rhasspy#52]
In 2.4 it would always ask me if I want to train now or later when I saved words, sentences. This is now gone and it trains directly instead. I really liked that feature because I could make changes in multiple places and then train only once, now I have to wait for training to finish for every change I make.

Restarting rhasspy is the same thing, once I click save in the settings tab it restarts. Most of the time that is useful but I actually managed to freeze my whole system by accidentally saving (and therefore restarting) while training was still running. Also I might want to just make a change, look at the advanced settings to see what it does and then undo the change again, or edit it further in the advanced settings, so having to restart two or more times in between is kinda annoying.

On a sidenote, some settings display a small red icon next to them after I change them (I am guessing to restart) but it restarts anyway once i click save, either the icon is not necessary or it wasn't intended to restart with every save.

Daenara

**Comment by synesthesiam** [comment]
Added this locally. Will be in the next release :+1:
