### ISSUE TITLE
MQTT issues

### ISSUE THREAD

**Issue by calvinthefreak** [rhasspy/rhasspy#55]
Hello Rhasspy devs, 

I've noticed some weird behaviour with mqtt... the problem here is, that I use IoBroker as my backend for everything, I use the integrated mqtt server addon that they provide (all updated to current version)
![grafik](https://user-images.githubusercontent.com/5560381/83954094-6b52ff80-a846-11ea-86eb-ad0d6c316056.png)
![grafik](https://user-images.githubusercontent.com/5560381/83954103-70b04a00-a846-11ea-9919-19a328b7a781.png)

there is still some weird behavior, I only use an remote rhasspy instance for kaldi reco (there I did not setup the mqtt --> so no collision problems)

so in conclusion: main rhasspy: on a Raspberry Pi setup with docker, Latest Version 2.4.20, that does mqtt, wakeword and tts and an rhasspy instance in an vm. also dockerized 2.4.20 for kaldi only.

![grafik](https://user-images.githubusercontent.com/5560381/83954124-9d646180-a846-11ea-846b-38d7575e4939.png)
This screenshot is my setup on the raspberry pi that does the wakeword and so on... but not the kaldi part...

Still are there Issues, where suddenly it reconnects to the mqttbroker without any disconnect message...
```log
[INFO:2669544] HermesMqtt: Connected to 10.150.1.107:1884
[INFO:2487798] HermesMqtt: Connected to 10.150.1.107:1884
[DEBUG:2342556] PorcupineWakeListener: started -> listening
[DEBUG:2342552] DialogueManager: ready -> asleep
[INFO:2342548] DialogueManager: Automatically listening for wake word
[DEBUG:2342542] DialogueManager: handling -> ready
```

And caused by this, sometimes very often, the intents will not be send to the broker, causing IoBroker not to update e.g. a state of a light...

If you have any further questions regarding logs or so on, then I can post it.

**Comment by calvinthefreak** [comment]
> Hello Rhasspy devs,
> 
> I've noticed some weird behaviour with mqtt... the problem here is, that I use IoBroker as my backend for everything, I use the integrated mqtt server addon that they provide (all updated to current version)
> ![grafik](https://user-images.githubusercontent.com/5560381/83954094-6b52ff80-a846-11ea-86eb-ad0d6c316056.png)
> ![grafik](https://user-images.githubusercontent.com/5560381/83954103-70b04a00-a846-11ea-9919-19a328b7a781.png)
> 
> there is still some weird behavior, I only use an remote rhasspy instance for kaldi reco (there I did not setup the mqtt --> so no collision problems)
> 
> so in conclusion: main rhasspy: on a Raspberry Pi setup with docker, Latest Version 2.4.20, that does mqtt, wakeword and tts and an rhasspy instance in an vm. also dockerized 2.4.20 for kaldi only.
> 
> ![grafik](https://user-images.githubusercontent.com/5560381/83954124-9d646180-a846-11ea-846b-38d7575e4939.png)
> This screenshot is my setup on the raspberry pi that does the wakeword and so on... but not the kaldi part...
> 
> Still are there Issues, where suddenly it reconnects to the mqttbroker without any disconnect message...
> `[INFO:2669544] HermesMqtt: Connected to 10.150.1.107:1884 [INFO:2487798] HermesMqtt: Connected to 10.150.1.107:1884 [DEBUG:2342556] PorcupineWakeListener: started -> listening [DEBUG:2342552] DialogueManager: ready -> asleep [INFO:2342548] DialogueManager: Automatically listening for wake word [DEBUG:2342542] DialogueManager: handling -> ready`
> 
> And caused by this, sometimes very often, the intents will not be send to the broker, causing IoBroker not to update e.g. a state of a light...
> 
> If you have any further questions regarding logs or so on, then I can post it.

**Comment by calvinthefreak** [comment]
![grafik](https://user-images.githubusercontent.com/5560381/83954572-a6573200-a84a-11ea-8676-fe113d5fee45.png)
For reference, this is the moment, when Rhasspy looses the connection, but I can't work out, why this happens...

**Comment by Daenara** [comment]
I think you have the wrong project for 2.4.20. This is the github of the new 2.5 version. The 2.4 github is [here](https://github.com/synesthesiam/rhasspy).

**Comment by calvinthefreak** [comment]
Ok, never mind, this was the official docker install described in the docs...
