### ISSUE TITLE
Slot substitutions do not work correctly for group

### ISSUE THREAD

**Issue by DanielWe2** [rhasspy/rhasspy#56]
For example the following in a slot file:

`(Bad|Badezimmer):light.bad  `

Will generate the following Slot in the Intent when you say "Badezimmer":

`slots=[Slot(entity='switch', value={'kind': 'Unknown', 'value': 'Badezimmer light.bad'}`

The same is happening with single word groups in ()

Rhasspy 2.5 final and Fsticuffs for intent recognition

**Comment by DanielWe2** [comment]
Addition it also happens in a case like:

`(Lampe im Badezimmer):light.bad `

**Comment by synesthesiam** [comment]
Short answer: lower case "Lampe", etc. for now

Long answer: Rhasspy tries to preserve the casing of your words by transforming them into substitutions during training. It looks like this interacts poorly with "real" substitutions, causing everything to get dumped into the output! Definitely a bug, but will need time to fix.

**Comment by synesthesiam** [comment]
Should be fixed now
