### ISSUE TITLE
[Feature Request] Preconfigure and add documentation for Home Assistant in the UI

### ISSUE THREAD

**Issue by DanielWe2** [rhasspy/rhasspy#59]
With the great new Rhasspy tutorial it is quite easy to setup Rhasspy on a new Pi. 

It will react to a wake word and parse intents. But actually doing something useful with the intents is still more complicated for Home Assistant users than it needs to be. 

### Suggestions:
1. Enable "Send intents" by default for Home Assistant. It is the intended way to do it now and more importantly:  There are some build in intents (https://developers.home-assistant.io/docs/intent_builtin)
2. Either change/add the initial default intents of Rhasspy to those builtin intent names or add them to the user configuration the first time the user enables Home Assistant Intent handling. 

Those two should should be very easy to do (at least the first option of suggestion 2).

#### Slots 

Those built in intents of Home Assistant need the names of the entities as Slot Value. I see two possibilities to help the user here:

1. In the Home Assistant intent handling configuration add a help text like (fix my english):
`To use the build in intents of Home Assistant together with the preconfigured sentences create a new slot "hassnames" in Rhasspy and paste the output of the following template (link to open text in a dialog) executed in the "Developer Tools/Template" tab in home assistant into it.`  
[hass-names.txt](https://github.com/rhasspy/rhasspy/files/4742011/hass-names.txt)
(another option is a more complex version instructing the user to create multiple slots for different types of entities with more than one template "script)
2. Provide a simple slot-generation-script that queries Home Assistant for all entities in the different domains (light, switch, cover, scenes, groups) using the configured API data and configure it when the user selects Home Assistant.

### Conclusion

Doing some of those things would greatly improve the out of the box experience with Home Assistant and provide the user with a working voice assistant without any configuration in Home Assistants files.

**Comment by synesthesiam** [comment]
I agree, I've switched to "Send Intents" as the default. Should be in the next release.

I'm working on an example here: https://github.com/rhasspy/rhasspy/tree/master/examples/homeassistant

This uses the built-in intents and automatically downloads entities using a slot program. Let me know what you think.
