### ISSUE TITLE
Hardcoded say_finished_timeout of 10 seconds is a problem 

### ISSUE THREAD

**Issue by DanielWe2** [rhasspy/rhasspy#62]
DialogueHermesMqtt uses a hard coded say timeout of ten seconds.

Ten seconds seems long but there are lots of plausible real word cases that need longer messages. I was playing around writing small game app. 

After intentNotRecognized I wanted it so say a help text explaining the possible options (the text is about 13 seconds long).    It triggered the timeout and Rhasspy started to listen to it's own speech leading to an infinite loop of intentNotRecognized events.

What is the point of the timeout?  To stop it in case the TTS system gets stuck? If that's the goal I think it should end the session and should not continue after the timeout. 

Possible fixes:
- Hardcode a way higher timeout value (100 seconds?) and end the session and go back to default state
- Remove the timeout 
- Set the timeout depending on the length of the text  (len(text)*0.1+5) for example 
- Let the user overwrite the timeout in the json payload (not compatible to the Hermes protocol?)

**Comment by synesthesiam** [comment]
This is a good issue that needs some discussion. You're right; the timeout is there in case the TTS system crashes or there is no TTS system (despite the user configuring "Hermes MQTT"). A timeout based on the text length isn't a bad idea. Profile options could also be added to increase the timeout.

One option I just thought of is to have the TTS respond immediately with a new message to tell the dialogue manager (or whoever is listening) that "all is well, wait at least this long". The TTS system gets the WAV data, so it knows precisely how long the utterance will take to speak.

The overall goal is to prevent what's happening to you right now -- having Rhasspy accidentally interpret TTS output as input to the STT system :/

**Comment by DanielWe2** [comment]
Regarding your idea of having the TTS response with a time estimation. That should work  and would allow for exact timeouts. But can we be sure that every possible TTS system is able to predict/announce the playback time?  Let's say someone wants to use their TV or smartwatch or something with a cloud TTS Api to say Rhasspys messages. Sure in that case one could always use some other method based on text length for example in this "cloud bridging client".

So, I think your idea is the better way to do it. But maybe the quick one (timeout = len(text)*x+y) is good enough in the mean time.

**Comment by synesthesiam** [comment]
I'm adding a `dialogue.say_chars_per_second` setting that will be used to dynamically compute the timeouts.

**Comment by synesthesiam** [comment]
Added in latest 2.5.10.
