### ISSUE TITLE
Error downloading Dutch (NL) Kaldi profile

### ISSUE THREAD

**Issue by ghost** [rhasspy/rhasspy#63]
Just did a clean install but it seems there are files missing on the kaldi github repository.

```
[DEBUG:2020-06-09 17:39:45,898] rhasspyprofile.download: Downloading https://github.com/synesthesiam/nl_kaldi-cgn/raw/master/acoustic_model/conf/ivector_extractor.conf to /profiles/nl/kaldi/model/conf/ivector_extractor.conf

[ERROR:2020-06-09 17:39:46,240] rhasspyprofile.download: Download failure (https://github.com/synesthesiam/nl_kaldi-cgn/raw/master/acoustic_model/conf/ivector_extractor.conf, got 169336 byte(s), expected 881)

[ERROR:2020-06-09 17:39:46,241] rhasspyserver_hermes: ('https://github.com/synesthesiam/nl_kaldi-cgn/raw/master/acoustic_model/conf/ivector_extractor.conf', 'File size mismatch (got 169336 byte(s), expected 881)')

Traceback (most recent call last):
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/quart/app.py", line 1821, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/quart/app.py", line 1869, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyserver_hermes/__main__.py", line 583, in api_download_profile
    ssl_context=ssl_context,
  File "/usr/lib/rhasspy/lib/python3.7/site-packages/rhasspyprofile/download.py", line 494, in download_files
    f"File size mismatch (got {final_size} byte(s), expected {bytes_expected})",

rhasspyprofile.download.DownloadFailedException: ('https://github.com/synesthesiam/nl_kaldi-cgn/raw/master/acoustic_model/conf/ivector_extractor.conf', 'File size mismatch (got 169336 byte(s), expected 881)')
```

Visiting the url gives a 404 Not Found.

**Comment by synesthesiam** [comment]
Got it, thanks. Wil be fixed in the next release.

**Comment by gisteren** [comment]
Hello,

Is there a temporarily fix that can be used. I have just thrown my pre-release away to find out that final release does not work with the nl kaldi profile.

Thanks

**Comment by synesthesiam** [comment]
I'm trying to get a new Docker image pushed with the fix. DockerHub is not being very cooperative...

**Comment by synesthesiam** [comment]
A temporary fix might be to download the missing files from an older commit: https://github.com/synesthesiam/nl_kaldi-cgn/tree/1e6d9dad9c16afdf91114f9e6e932428b522488b/acoustic_model/conf

**Comment by gisteren** [comment]
> I'm trying to get a new Docker image pushed with the fix. DockerHub is not being very cooperative...

I am using the debian package and not the docker image. 

If I implement it from the source, is the fix in there already?

**Comment by synesthesiam** [comment]
Yes, the fix is in `master` already.

I'm in the process of changing the download links in each profile to refer to a specific commit instead of `master`. I hadn't realized before that this would be a problem if profile files were removed or updated while someone was using a version of Rhasspy that hadn't been updated.

**Comment by Romkabouter** [comment]
@NoedelVreter this is probably fixed, can you verify?
