### ISSUE TITLE
Upgrade porcupine to version 1.8

### ISSUE THREAD

**Issue by gitmirko** [rhasspy/rhasspy#65]
Hi,
it seems that procupine v1.8 should perform [quite well](https://picovoice.ai/blog/porcupine-wake-word-engine-v1-8-feature-tour/) and it would be nice to have it available in rhasspy.

Keep up the great work.

Best regards
Mirko

**Comment by Tooa** [comment]
Thanks for bringing this up @gitmirko. I've created a pull request to update to the new version. If you like you can test this [here](https://github.com/rhasspy/rhasspy-wake-porcupine-hermes/pull/3).

**Comment by synesthesiam** [comment]
Merged into `master`. Will be in next version :)

**Comment by KiboOst** [comment]
no way, one custom wakeword and valid only for 30days. Won't even try it, totally useless :-(

**Comment by Tooa** [comment]
> no way, one custom wakeword and valid only for 30days. Won't even try it, totally useless :-(

Can you elaborate more on this? Any source?
