### ISSUE TITLE
Error when disabling fuzzywuzzy

### ISSUE THREAD

**Issue by alexbarcelo** [rhasspy/rhasspy#69]
The following line seem to be responsible for an error when `--disable-fuzzywuzzy` is specified in the `./configure` command:

https://github.com/rhasspy/rhasspy/blob/2ada4ad99ed6f04103e833254504e21995094849/setup.py.in#L57

~Maybe that's related to the package change to `rapidfuzz`? Is that right? If that's the issue, then the change seems simple... but I am not sure if I'm on the wrong here.~

Is the problem that the hyphen (`-`) should be an underscore (`_`) ?

**Comment by synesthesiam** [comment]
Yes, the "-" should be a "_" :facepalm: 

Thanks :+1:

**Comment by alexbarcelo** [comment]
I was just realizing that as you were writing it xD --see my edit.

**Comment by alexbarcelo** [comment]
Fixed by 876c8ab339d95b833bdb05a305317b9c94b9ad30
