### ISSUE TITLE
[Feature Request] Support for Mozilla's TTS

### ISSUE THREAD

**Issue by Mic92** [rhasspy/rhasspy#70]
Mozilla's TTS is the best open-source text-to-speech engine for English, I tried so far. Without a GPU it is currently a bit slow. However they are about to embed the vocoder, which would make the generation faster:
https://github.com/mozilla/TTS/pull/415

**Comment by synesthesiam** [comment]
Check out [OpenTTS](https://github.com/synesthesiam/opentts#adding-marytts-and-mozilla-tts) (Docker). It has an example of how to run MozillaTTS through Docker. It's CPU only right now, so a bit slow.

If they get the new vocoder in, I'll definitely update the MozillaTTS Docker image :+1:

**Comment by Mic92** [comment]
I am aware of opentts, but would it not make sense to just integrate the http call directly into `rhasspy-tts-cli-hermes`?

**Comment by Mic92** [comment]
We are also packaging `TTS` for nix: https://github.com/mweinelt/nixpkgs/commits/tts but it is probably a good idea to wait for the mozilla/TTS#415 to be upstream before merging it.

**Comment by synesthesiam** [comment]
The OpenTTS API is actually copied from MozillaTTS, so you can just point it at the MozillaTTS server and it should work :)

**Comment by Mic92** [comment]
Oh, that's nice, but also unexpected. Should I make a PR that just adds a UI menu point for mozilla TTS? It would be the same backend in the end for now (in future mozilla's API might diverge; I don't think they have a stable API right now)

**Comment by synesthesiam** [comment]
Sure, a PR would be great. Thanks.
