### ISSUE TITLE
bool converter not working

### ISSUE THREAD

**Issue by parasaurolophus** [rhasspy/rhasspy#78]
The `bool` converter always emits `true` regardless of the input value (e.g. "false", 0).

Observed using Docker image of 2.5.0 running on amd64 host hardware, Ubuntu 20.04 host OS.

**Comment by synesthesiam** [comment]
Fixed in https://github.com/rhasspy/rhasspy-nlu/commit/3d3e2d3f1528385a7f3e5d6f55f2b8d8942babd3

The `bool` converter will now return `False` for zero and the string `"false"` (case insensitive).

This will be merged into Rhasspy 2.5.1
