### ISSUE TITLE
log is not available

### ISSUE THREAD

**Issue by j3mu5** [rhasspy/rhasspy#8]
Log is almost never displayed under Chrome and not under Firefox, the window "Rhasspy Log" remains empty. Only rarely a log is displayed, I did not fully understand the system. I think, if you have Rhasspy open in your browser and restart it via docker you will see a stream. But I was not able to repeat this in a reproducible way.

If you try to stream the log over a websocket (ws://IP:PORT/api/events/log), it stops at the status "Opening". This is the case for the following 2 extensions under Chrome: Simple Websocket Client, Browser Websocket Client

I also had problems with audio recording and playback - I couldn't get either of them to work. Unfortunately I cannot say more without log.

**Comment by Xalip** [comment]
Did you exec into the docker container and tried `arecord -l` and `aplay -l`? Are your devices listed then? It's super confusing in my case as well. I'm able to see my device and my mic is working. Running `speaker-test` inside the docker container is working as well. But I can't hear the wakebutton sound of rhasspy after hitting the button.

**Comment by j3mu5** [comment]
Yes, inside the docker container I can see my audio devices with the commands "arecord -l" and "aplay -l". The speaker-test also works without problems from docker. 

With Rhasspy 2.4.19 everything works without problems.

@Xalip EDIT: If the wake word is recognized (porcupine) you hear the wake word with pre-2.5. 

You can hear the error sound if you enter a nonsensical text on the main page under "Text to recognise" which cannot be assigned to any intent and click on "Get intent".

Sounds work, they are just not always triggered as usual / expected.

I have integrated my sounds as follows:
${RHASSPY_PROFILE_DIR}/wav/wake.wav
${RHASSPY_PROFILE_DIR}/wav/recorded.wav
${RHASSPY_PROFILE_DIR}/wav/error.wav

**Comment by synesthesiam** [comment]
Websocket log issue should be fixed now. Hopefully audio recording is also fixed for you.

**Comment by j3mu5** [comment]
@synesthesiam 
Thanks a lot - with Log testing is much more fun! I have the audio under control now. ᕙ༼*◕_◕*༽ᕤ
