### ISSUE TITLE
wake-word#porcupine - unnecessary profile updates

### ISSUE THREAD

**Issue by keith721** [rhasspy/rhasspy#80]
https://github.com/rhasspy/rhasspy/blob/master/docs/wake-word.md#porcupine

Raspberry Pi 4
Debian Buster
JabraSpeak 410 USB

The following three lines are completely unnecessary, and only served to cause errors/frustration when I setup my RPi 4 with Rhasspy 2.5.0 this week.  I suggest marking these as completely optional settings.  Thanks!!
```
    "library_path": "porcupine/libpv_porcupine.so",
    "model_path": "porcupine/porcupine_params.pv",
    "keyword_path": "porcupine/porcupine.ppn",
```

**Comment by synesthesiam** [comment]
Good point. I'll update the docs :+1:
