### ISSUE TITLE
simple command needed

### ISSUE THREAD

**Issue by infinitymakerspace** [rhasspy/rhasspy#81]
I need to add a simple command to trigger a relay via node-red that is already on a timer of 20 seconds in node-red.  I am battling to get any straight forward examples. I have tried to use a state change but training shows errors

**Comment by koenvervloesem** [comment]
What errors?

**Comment by infinitymakerspace** [comment]
Let me simplify....

I want to say dispense

And I want to use it as a trigger input word for node red to engage a flow
that has its own timer that halts after 20 seconds.

**Comment by synesthesiam** [comment]
You may want to try [voice2json](https://voice2json.org) with the [community contributed add-on](https://github.com/johanneskropf/node-red-contrib-voice2json)

**Comment by infinitymakerspace** [comment]
> You may want to try [voice2json](https://voice2json.org) with the [community contributed add-on](https://github.com/johanneskropf/node-red-contrib-voice2json)

Many thanks, working on it but having installation issues attempting to build from source have given me issues which I followed up with voice2json devs via Github.
