### ISSUE TITLE
Cancel pattern

### ISSUE THREAD

**Issue by mweinelt** [rhasspy/rhasspy#85]
Every once in a while my voice assistant triggers unintentionally. What can I say to cancel those requests? I found the idea of cancel patterns a good match. Basically saying "Abort!" or "Stop!" could prevent random events from being fired.

Idea comes from here https://github.com/Psychokiller1888/MyChef/tree/master/assistants/assistant_fr/custom_dialogue/speak.

Is there anything like this already possible?

**Comment by synesthesiam** [comment]
You could just create an intent that's triggered by those words (or a custom phrase) and not doing anything in response to it in HA or Node-RED (or whatever you're using to handle intents). Something like:

```ini
[AbortRequest]
abort | stop | cancel
```

Does the linked assistant do anything special with the cancel pattern?

**Comment by mweinelt** [comment]
That was snips apparently, I have no clue and since they've been bought *shrug*.

The AbortRequest sounds like a low effort workaround, so let's do that instead.
