### ISSUE TITLE
No matching distribution found for rhasspy-server-hermes~=2.5.3 (from rhasspy==2.5.2)

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#87]
idem after update  Version 2.5.2 is up: https://pypi.org/project/rhasspy-server-hermes/
new message
ERROR: Could not find a version that satisfies the requirement rhasspy-server-hermes~=2.5.3 (from rhasspy==2.5.2) (from versions: 2.5.0, 2.5.1, 2.5.2)
ERROR: No matching distribution found for rhasspy-server-hermes~=2.5.3 (from rhasspy==2.5.2)
make: *** [Makefile:153: install-rhasspy] Error 1

**Comment by lricher1** [comment]
+1

**Comment by synesthesiam** [comment]
Please follow discussion here: https://github.com/rhasspy/rhasspy/issues/84
