### ISSUE TITLE
Train displays error

### ISSUE THREAD

**Issue by MartinMaier** [rhasspy/rhasspy#9]
I'm using Kaldi as text to speech and every train leeds to an error. 
[train error.log](https://github.com/rhasspy/rhasspy-voltron/files/4365123/train.error.log)

**Comment by synesthesiam** [comment]
Please try again with the latest build and let me know. Thanks.

**Comment by MartinMaier** [comment]
I did a fresh install with the last image but the error ist still the same.

**Comment by MartinMaier** [comment]
Hi synesthesiam, I did a lot of tests, playing around with the syntax within sentences.ini. Finally I got the train to run without any errors. I removed all 'Rules' like 'devicestate = ( ein| aus ) {state}' and placed that values into slots. Thats it. Now the Train runs without any error.

**Comment by synesthesiam** [comment]
Should work as long as the rules are declared inside of an intent. Weird.

**Comment by MartinMaier** [comment]
Hi synesthesiam,
I think the syntax should be ok ...
[sentences_which_which_leads_to_errror_ini.txt](https://github.com/rhasspy/rhasspy-voltron/files/4423174/sentences_which_which_leads_to_errror_ini.txt)

**Comment by synesthesiam** [comment]
He @MartinMaier, your example sentences are working for me with the latest Rhasspy now.

I did have to force the encoding to be UTF-8, but after that (and adding made-up $devicelist and $channellist slots), it trained successfully.
