### ISSUE TITLE
Installation issue (using WSL)

### ISSUE THREAD

**Issue by achintyaakumar** [rhasspy/rhasspy#94]
Hello, I was trying to install on WSL by following the guide (https://rhasspy.readthedocs.io/en/latest/installation/#windows-subsystem-for-linux-wsl) and ran the `make install` command, after that I tried to go to `http://localhost:12101` but it says that the page isn't working. Is there a step that I'm missing or something I did wrong? I'm new to Linux so my error might be silly, but I've been searching for a solution for hours now. Thanks in advance!

**Comment by koenvervloesem** [comment]
Did you run the `rhasspy` command after installation? Does it show any error messages?

**Comment by achintyaakumar** [comment]
Thanks for your response @koenvervloesem. Yes, I did and it says `rhasspy: command not found` i think I might've not added it to path correctly. Is there any other step that I could be missing?

**Comment by koenvervloesem** [comment]
Yes, adding the location of the `rhasspy` binary to your path should be the first thing to try.

**Comment by achintyaakumar** [comment]
I have many different ways but it says that the command was not found. Is there a command you recommend or some resource you could point me to? That would be highly helpful. Thanks and stay safe!
